// Generated by `npm run party-quiz`; edit fields only; comments are not kept.
import type { PartyQuizSheet } from '@shared/partyQuiz';

export const sheet: PartyQuizSheet = {
  "party": "Aontú",
  "election": "ge2024",
  "documents": [
    "aontu-ge2024-p1",
    "aontu-ge2024-p2"
  ],
  "model": "deepseek-flash",
  "promptVersion": "v2",
  "items": [
    {
      "questionId": 1,
      "fingerprint": "1ef56c01",
      "rationale": "Aontú prioritises state-led building of social and affordable homes and major water infrastructure investment, matching answer 0 over tax relief, social supports or reserves.",
      "modelConfidence": 0.7,
      "review": "approved",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "aontu-ge2024-p1",
          "page": 7,
          "pageLabel": null,
          "text": "We will build 15,000 social and affordable homes a year for the life of the next Dáil.",
          "quoteSha": "37f7021f180d6975"
        },
        {
          "document": "aontu-ge2024-p1",
          "page": 12,
          "pageLabel": null,
          "text": "Aontú in government would invest €3.5bn in the provision of clean and wastewater next year making it possible to build tens of thousands of new homes.",
          "quoteSha": "64ca736733ecaf52"
        }
      ]
    },
    {
      "questionId": 2,
      "fingerprint": "d9a4ede8",
      "rationale": "The documents discuss enterprise policy, FDI dependence, and corporation tax reliance but do not state a position on the 12.5% rate, EU minimum rate, raising headline rates, or pivoting from tax competition.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 3,
      "fingerprint": "ef513b0e",
      "rationale": "The documents discuss infrastructure investment and PPP costs but do not state a position on how to deliver a €10bn rail upgrade via PPP or exchequer.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 4,
      "fingerprint": "559f8cbf",
      "rationale": "Aontú proposes state-directed price reduction and VAT zero-rating on electricity, shielding all households from high prices rather than targeted rebates or income supports. This matches answer 0 best.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "aontu-ge2024-p1",
          "page": 42,
          "pageLabel": null,
          "text": "Aontú will mandate the ESB, which is making extraordinarily high profits, to reduce their profit levels and lower the cost of electricity.",
          "quoteSha": "d82c243df4ddfb5c"
        },
        {
          "document": "aontu-ge2024-p1",
          "page": 37,
          "pageLabel": null,
          "text": "Zero rate Electricity on VAT while electricity prices remain high.",
          "quoteSha": "fc33c822e294b477"
        }
      ]
    },
    {
      "questionId": 5,
      "fingerprint": "bb8e1c30",
      "rationale": "Aontú backs parental and school ethos choice in a pluralist system, and requires SPHE materials to respect that ethos, matching answer 1's blend of pluralism with continuity for faith schools and ethical debate.",
      "modelConfidence": 0.7,
      "review": "approved",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "aontu-ge2024-p2",
          "page": 16,
          "pageLabel": null,
          "text": "Aontú believe in a pluralist education system in Ireland. Parents should be able to choose the ethos, within reason, within which their children receive education.",
          "quoteSha": "a11f856d66e898dc"
        },
        {
          "document": "aontu-ge2024-p2",
          "page": 17,
          "pageLabel": null,
          "text": "Aontú will ensure that all SPHE and associated materials adhere to the ethos of the parents and schools their children are being taught in.",
          "quoteSha": "2977979814617d77"
        }
      ]
    },
    {
      "questionId": 6,
      "fingerprint": "a3c40286",
      "rationale": "The document proposes state payment per patient engagement to providers, a funding reset that funds people rather than systems, matching vouchers/patient choice over a fully public state-run model.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "answered",
      "answerIndex": 3,
      "abstainReason": null,
      "quotes": [
        {
          "document": "aontu-ge2024-p1",
          "page": 17,
          "pageLabel": null,
          "text": "Aontú seeks to change the funding of the health service to a patient engagement model. Where a patient receives an operation, a treatment, an engagement or a consultation, the state will pay the provider.",
          "quoteSha": "ea1c3aa74d7f537f"
        }
      ]
    },
    {
      "questionId": 7,
      "fingerprint": "7a9221d8",
      "rationale": "Documents oppose expanding abortion rights (protect 3-day wait) and oppose censorship laws, but do not address a bill expanding speech, assembly and reproductive rights together, so no single answer matches.",
      "modelConfidence": 0.3,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "no_preference",
      "quotes": []
    },
    {
      "questionId": 8,
      "fingerprint": "f7fb5915",
      "rationale": "Aontú links migrant hosting to community investment, but the documents never pair Irish-language funding with migrant integration programmes, so no answer is clearly matched.",
      "modelConfidence": 0.3,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "no_preference",
      "quotes": []
    },
    {
      "questionId": 9,
      "fingerprint": "21820e1a",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 10,
      "fingerprint": "308af8e2",
      "rationale": "The documents do not address arts funding or cultural policy in any form.",
      "modelConfidence": 1,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 11,
      "fingerprint": "cb14689e",
      "rationale": "The manifesto rejects any move toward a military alliance and treaty change, matching answer 2's refusal to join and protection of neutrality over collective defence.",
      "modelConfidence": 0.85,
      "review": "approved",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "aontu-ge2024-p2",
          "page": 28,
          "pageLabel": null,
          "text": "Aontú opposes treaty change. Aontú opposes any moves towards a military alliance.",
          "quoteSha": "2623d7d3c2bb90f7"
        }
      ]
    },
    {
      "questionId": 12,
      "fingerprint": "dc35f0f4",
      "rationale": "Aontú opposes the EU Nature Restoration Law as a threat to farmers and resists EU encroachment, but accepts EU obligations, indicating opposition to centralisation while not seeking full withdrawal.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "aontu-ge2024-p2",
          "page": 38,
          "pageLabel": null,
          "text": "This EU law, which was supported by the Government parties, and welcomed by a Sinn Féin MEP, is pointed directly at Ireland.",
          "quoteSha": "92b14d286a7abc48"
        },
        {
          "document": "aontu-ge2024-p2",
          "page": 38,
          "pageLabel": null,
          "text": "We will insist that state owned land be used to ensure Ireland meets its EU obligations.",
          "quoteSha": "265191cfa4ea116b"
        }
      ]
    },
    {
      "questionId": 13,
      "fingerprint": "a7b1e486",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.4,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 3
    },
    {
      "questionId": 14,
      "fingerprint": "e081e7eb",
      "rationale": "Documents oppose the Climate Action Bill and are alarmed by a suggested 30% herd cull, prioritising farmers over climate targets, matching answer 3 (relax timelines to protect rural livelihoods).",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "answered",
      "answerIndex": 3,
      "abstainReason": null,
      "quotes": [
        {
          "document": "aontu-ge2024-p2",
          "page": 35,
          "pageLabel": null,
          "text": "Aontú was the only political party to oppose the Climate Action Bill in the Dáil. We did as we knew this Bill would increase pressure on farmers.",
          "quoteSha": "521537a8ad86274d"
        },
        {
          "document": "aontu-ge2024-p2",
          "page": 35,
          "pageLabel": null,
          "text": "Aontú is extremely alarmed at the content of a report from the Environmental Protection Agency last year which suggests that a national herd cull of 30% would be required to meet climate targets.",
          "quoteSha": "c5df20a6e4cb377e"
        }
      ]
    },
    {
      "questionId": 15,
      "fingerprint": "a2d8f793",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 16,
      "fingerprint": "25dadce4",
      "rationale": "The documents discuss tolls, commuter hell, and public transport investment but never mention congestion charges or any of the four policy options.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 17,
      "fingerprint": "471a3337",
      "rationale": "The documents do not mention facial recognition, Garda surveillance technology, or biometric policing anywhere, so no position on the question can be drawn from them.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 18,
      "fingerprint": "edec1d4e",
      "rationale": "The documents do not address protests blocking infrastructure or how to respond to such disruption.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 19,
      "fingerprint": "7842be43",
      "rationale": "The documents do not address pandemic response, public health restrictions, or any related approach to managing a new variant.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 20,
      "fingerprint": "f62bbcbf",
      "rationale": "The documents do not mention universal basic income or any pilot, replacement, or rejection of it; welfare proposals are targeted and unrelated to UBI.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 21,
      "fingerprint": "1609def7",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 1
    },
    {
      "questionId": 22,
      "fingerprint": "e1fb2ebb",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 23,
      "fingerprint": "3ec07b23",
      "rationale": "Documents stress ministerial sign-off, accountability and scrutiny of spending, not AI simulations. No passage addresses AI-driven policy tools, so the party is silent on the question.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 24,
      "fingerprint": "c06f1dff",
      "rationale": "The documents do not address citizens' assemblies or their authority over reforms.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 25,
      "fingerprint": "07c9b0b9",
      "rationale": "Aontú proposes changing senior civil servants' job specs to include accountability for value for money, with disciplinary consequences up to dismissal for failure, matching answer 0's performance contracts and consequences.",
      "modelConfidence": 0.8,
      "review": "approved",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "aontu-ge2024-p1",
          "page": 50,
          "pageLabel": null,
          "text": "We will change job specifications of all senior civil servants so they have a responsibility to mind the public purse and ensure value for money for taxpayers.",
          "quoteSha": "ef996af16c729e3b"
        },
        {
          "document": "aontu-ge2024-p1",
          "page": 50,
          "pageLabel": null,
          "text": "Where they fail, there must be disciplinary measures up to and including losing their job.",
          "quoteSha": "800eb1e645dc0eb0"
        }
      ]
    },
    {
      "questionId": 27,
      "fingerprint": "3ab3cc9b",
      "rationale": "The documents do not address assisted dying or end-of-life legislation; the closest content concerns abortion and the right to life, which is a different question.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 28,
      "fingerprint": "fab89ead",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.7,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 29,
      "fingerprint": "3a36420a",
      "rationale": "The manifesto explicitly commits to protecting the existing three-day waiting period, matching answer 2's support for a three-day wait for reflection.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "aontu-ge2024-p2",
          "page": 15,
          "pageLabel": null,
          "text": "Aontú will protect the 3 day wait period for mothers who are contemplating abortion.",
          "quoteSha": "052eaaa6f531bbc5"
        }
      ]
    },
    {
      "questionId": 30,
      "fingerprint": "429bf7e6",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.4,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 2
    },
    {
      "questionId": 31,
      "fingerprint": "095134aa",
      "rationale": "The documents do not address surrogacy or any related assisted reproduction policy.",
      "modelConfidence": 1,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 32,
      "fingerprint": "6ac7c9a0",
      "rationale": "The documents do not mention the Angelus, RTÉ's daily religious broadcast, or any policy on broadcasting a religious devotion or moment of reflection.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 33,
      "fingerprint": "4e33e0ca",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 1
    },
    {
      "questionId": 34,
      "fingerprint": "7f8a2d2c",
      "rationale": "The documents do not address the naming of streets, bridges or public spaces, nor whose stories such names should tell.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 35,
      "fingerprint": "2d90c7e8",
      "rationale": "The documents address online child protection only through banning online pornography provision to children, not age verification or under-16 bans, so they do not choose between the answers.",
      "modelConfidence": 0.2,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "no_preference",
      "quotes": []
    },
    {
      "questionId": 36,
      "fingerprint": "fc63dfdb",
      "rationale": "The documents discuss crime, courts, sentencing and Garda reform but never mention non-jury courts, the Special Criminal Court, juror intimidation or jury trials.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 37,
      "fingerprint": "37d5e83d",
      "rationale": "The documents discuss Garda numbers, assaults, and sentencing but do not address stop-and-search powers or reasonable suspicion requirements.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 38,
      "fingerprint": "e90d2e5d",
      "rationale": "The documents discuss energy, grid investment and enterprise but never address data centres or how new ones should be connected to the electricity grid.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 39,
      "fingerprint": "206cd4cf",
      "rationale": "Both passages commit to pausing/stalling carbon tax increases while costs are high, matching answer 2 rather than raising, keeping the path, or freezing then cutting.",
      "modelConfidence": 0.85,
      "review": "approved",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "aontu-ge2024-p1",
          "page": 37,
          "pageLabel": null,
          "text": "Aontú will reverse the last two Excise increases on petrol and diesel and pause all carbon tax increases until the cost of living crisis subsides.",
          "quoteSha": "d4721e49a76781e7"
        },
        {
          "document": "aontu-ge2024-p1",
          "page": 38,
          "pageLabel": null,
          "text": "Aontú will stall the carbon tax rises, until such time as the price of fuel has consistently dropped and reverse the last rise.",
          "quoteSha": "b7907f8ab0fe263e"
        }
      ]
    },
    {
      "questionId": 40,
      "fingerprint": "90aed241",
      "rationale": "The documents do not address rules or incentives for heating systems in existing homes.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 41,
      "fingerprint": "7105e74f",
      "rationale": "The documents discuss pensions only in terms of linking contributions and residency, not the State Pension age or retirement age. No position on changing the age is stated.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 42,
      "fingerprint": "00dc0e15",
      "rationale": "A universal weekly fee cap matches answer 1, and the means-tested second child benefit elsewhere targets lower incomes, so support is capped for all with extra help for those on lower incomes.",
      "modelConfidence": 0.7,
      "review": "approved",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "aontu-ge2024-p2",
          "page": 7,
          "pageLabel": null,
          "text": "Aontú will provide a cap for childcare costs of €100 a week.",
          "quoteSha": "1f306a87703bae45"
        },
        {
          "document": "aontu-ge2024-p2",
          "page": 7,
          "pageLabel": null,
          "text": "We will make €3,000 childcare subvention available to mothers and fathers who choose to stay at home within the first 3 years of the child's life.",
          "quoteSha": "838b60fc7490e12d"
        }
      ]
    },
    {
      "questionId": 43,
      "fingerprint": "f906fd37",
      "rationale": "The documents do not address jobseeker's payments linked to previous pay or their generosity/duration.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 44,
      "fingerprint": "396fad74",
      "rationale": "Aontú opposes the Mercosur trade deal because it exposes Irish beef farmers to cheaper South American imports, prioritising domestic producers over trade access. This matches answer 3.",
      "modelConfidence": 0.85,
      "review": "rejected",
      "status": "answered",
      "answerIndex": 3,
      "abstainReason": null,
      "quotes": [
        {
          "document": "aontu-ge2024-p2",
          "page": 35,
          "pageLabel": null,
          "text": "Aontú is opposed to the Mercosur Trade Deal which will see the Irish Beef market in Europe replaced by the South American market.",
          "quoteSha": "ea69da6842d92798"
        },
        {
          "document": "aontu-ge2024-p2",
          "page": 35,
          "pageLabel": null,
          "text": "This deal will crush the Irish farmer and will do untold damage to the environment.",
          "quoteSha": "1434dcfe2b4a774d"
        }
      ],
      "reviewNote": "Rejected 2026-10-05 after an independent read of the manifesto (weak): Manifesto opposes only the Mercosur deal; option 3 generalises to all deals. Option 2 fits about equally."
    },
    {
      "questionId": 45,
      "fingerprint": "14dff138",
      "rationale": "The documents do not address overseas aid spending or the 0.7% UN target anywhere in the manifesto text.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 46,
      "fingerprint": "0dbe2725",
      "rationale": "Aontú opposes EU treaty change and wants foreign policy devolved to nation states, rejecting majority voting and defending national veto/self-determination, matching keeping the veto.",
      "modelConfidence": 0.7,
      "review": "approved",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "aontu-ge2024-p2",
          "page": 28,
          "pageLabel": null,
          "text": "Aontú opposes treaty change. Aontú opposes any moves towards a military alliance.",
          "quoteSha": "2623d7d3c2bb90f7"
        },
        {
          "document": "aontu-ge2024-p2",
          "page": 28,
          "pageLabel": null,
          "text": "Aontú seeks to devolve Foreign Policy back to the nations states.",
          "quoteSha": "23537e2d12f21c7f"
        }
      ]
    },
    {
      "questionId": 47,
      "fingerprint": "6bdbf910",
      "rationale": "The documents do not address whether the Taoiseach should be able to appoint outside experts as ministers; no passage discusses ministerial eligibility or appointment from outside the Oireachtas.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 48,
      "fingerprint": "afb38ef2",
      "rationale": "The documents discuss referendums on specific topics such as Irish unity and the Care Referendum, but do not address whether citizens should be able to trigger a referendum.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 49,
      "fingerprint": "16abd67c",
      "rationale": "The documents discuss housing, banking reform and accountability generally, but never address who should set Central Bank mortgage lending limits. No position matching any answer is stated.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    }
  ]
};
