// Generated by `npm run party-quiz`; edit fields only; comments are not kept.
import type { PartyQuizSheet } from '@shared/partyQuiz';

export const sheet: PartyQuizSheet = {
  "party": "Fianna Fáil",
  "election": "ge2024",
  "documents": [
    "ff-ge2024"
  ],
  "model": "deepseek-flash",
  "promptVersion": "v2",
  "items": [
    {
      "questionId": 1,
      "fingerprint": "1ef56c01",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.75,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 2,
      "fingerprint": "d9a4ede8",
      "rationale": "The manifesto commits to a competitive tax position and to broadening R&D tax credits for innovation, matching answer 1's blend of compliance with targeted incentives rather than raising headline rates or state-led industry.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 15,
          "pageLabel": null,
          "text": "Give workers a break and keep Ireland’s income tax position competitive and sustainable for the long-term.",
          "quoteSha": "5eb4b3fb0ff1f1fe"
        },
        {
          "document": "ff-ge2024",
          "page": 16,
          "pageLabel": null,
          "text": "Expand and broaden the R&D tax credit to include innovation and digitalisation, building on the review announced in Budget 2025.",
          "quoteSha": "c7a0a0f764dd37e2"
        }
      ]
    },
    {
      "questionId": 3,
      "fingerprint": "ef513b0e",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 1
    },
    {
      "questionId": 4,
      "fingerprint": "559f8cbf",
      "rationale": "State absorbs network and PSO costs to cut bills, matching answer 0's state-funded shielding of every household, rather than targeted rebates, conservation tariffs, or income-only supports.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 24,
          "pageLabel": null,
          "text": "Fund the upgrading of the national electricity grid using State subventions so that domestic electricity customers will not have to pay for the upgrades through their electricity bills.",
          "quoteSha": "060ff3b01c19d201"
        },
        {
          "document": "ff-ge2024",
          "page": 24,
          "pageLabel": null,
          "text": "Switch to direct State funding of the Renewable Electricity Support Scheme, reducing Public Service Obligation (PSO) levy on households’ electricity bills by an average of €40.",
          "quoteSha": "71bc215c32a09926"
        }
      ]
    },
    {
      "questionId": 5,
      "fingerprint": "bb8e1c30",
      "rationale": "The manifesto stresses media literacy, online safety and practical civic skills in the curriculum, matching answer 2 rather than rights-focused or locally devolved approaches.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 187,
          "pageLabel": null,
          "text": "Publish the National Counter Disinformation Strategy and an implementation plan to empower citizens through media literacy, education, and awareness so they have the skills to identify disinformation.",
          "quoteSha": "7c09119b98c9727a"
        },
        {
          "document": "ff-ge2024",
          "page": 100,
          "pageLabel": null,
          "text": "We have reformed the curriculum to ensure that all students receive the information they need about drugs and alcohol, safe internet usage, relationships, consent, and healthy lifestyles.",
          "quoteSha": "2869df4a050ff01f"
        }
      ]
    },
    {
      "questionId": 6,
      "fingerprint": "a3c40286",
      "rationale": "The manifesto commits to removing routine private care from public hospitals, moving toward a more public system, though it does not endorse full state-run structural upheaval. This best matches answer 0 over the mixed or market-based options.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 55,
          "pageLabel": null,
          "text": "Further progress the work to remove routine private care from public hospitals.",
          "quoteSha": "f5b84daf8f5268dd"
        }
      ]
    },
    {
      "questionId": 7,
      "fingerprint": "7a9221d8",
      "rationale": "The manifesto addresses equality, LGBTQI+ health, and conversion practices, but never mentions a personal freedoms bill, speech, assembly, or reproductive rights. No stated position matches any answer.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 8,
      "fingerprint": "f7fb5915",
      "rationale": "The manifesto promotes Irish as a living community language and supports programmes increasing direct engagement between new arrivals and host communities in social, cultural and sporting activities, matching community-led cultural pairing.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 175,
          "pageLabel": null,
          "text": "Is é cuspóir bunaidh de chuid Fhianna Fáil an Ghaeilge a chur chun cinn mar theanga bheo phobail",
          "quoteSha": "7d7b064aa3bbdaeb"
        },
        {
          "document": "ff-ge2024",
          "page": 123,
          "pageLabel": null,
          "text": "Support programmes which increase the level of direct engagement between new arrivals and host communities in broader social, cultural and sporting activities.",
          "quoteSha": "a4a99483288d8211"
        }
      ]
    },
    {
      "questionId": 9,
      "fingerprint": "21820e1a",
      "rationale": "The manifesto prioritises radical planning reform and faster home delivery, with no mention of heritage preservation or citizens' votes, so it best matches aggressive rezoning and densification over preservation.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 31,
          "pageLabel": null,
          "text": "Central to our approach has been radical reform of planning laws and giving active priority to first time buyers and those seeking social and affordable housing.",
          "quoteSha": "2d14f5478c189671"
        },
        {
          "document": "ff-ge2024",
          "page": 32,
          "pageLabel": null,
          "text": "Immediately implement our landmark Planning and Development Act, including recruitment of 400 additional planning staff to deliver homes faster.",
          "quoteSha": "67da1a1972301f9c"
        }
      ]
    },
    {
      "questionId": 10,
      "fingerprint": "308af8e2",
      "rationale": "The manifesto prioritises community arts and participation alongside excellence, with capital funding for local and community arts, matching answer 1 over flagship-first, economic-impact or private-patronage approaches.",
      "modelConfidence": 0.75,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 162,
          "pageLabel": null,
          "text": "Establish an Arts Capital and Equipment Programme to invest in local and community arts.",
          "quoteSha": "cf689931a585a052"
        },
        {
          "document": "ff-ge2024",
          "page": 162,
          "pageLabel": null,
          "text": "The challenge ahead is to ensure a strategy that supports community arts and participation while also encouraging, protecting and promoting excellence.",
          "quoteSha": "ccf5d4ac9659ddc6"
        }
      ]
    },
    {
      "questionId": 11,
      "fingerprint": "cb14689e",
      "rationale": "The manifesto commits to protecting military neutrality while allowing only 'sensible reform' of the Triple Lock, which governs overseas deployments. This aligns with declining combat participation and prioritising peacekeeping, rather than joining a rapid-response force.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 128,
          "pageLabel": null,
          "text": "Continue to protect and promote Ireland’s military neutrality including sensible reform of the ‘Triple Lock’ legislation.",
          "quoteSha": "8892bdc31f0e0140"
        }
      ]
    },
    {
      "questionId": 12,
      "fingerprint": "dc35f0f4",
      "rationale": "The party broadly engages with EU agri policy (CAP funding, climate goals) but insists on a specific national carve-out, the Nitrates Derogation, recognising Irish farming's unique grass-based system. This matches answer 1, not full harmonisation or outright opposition.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 136,
          "pageLabel": null,
          "text": "Fianna Fáil is absolutely committed to securing the retention of Ireland’s Nitrates Derogation at EU level, while improving our water quality.",
          "quoteSha": "f9c1d709d478a7e7"
        },
        {
          "document": "ff-ge2024",
          "page": 134,
          "pageLabel": null,
          "text": "Fight at European level for a fully funded budget in the next CAP and reject any proposals to undermine CAP funding.",
          "quoteSha": "75d10d7a202feab7"
        }
      ]
    },
    {
      "questionId": 13,
      "fingerprint": "a7b1e486",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 2
    },
    {
      "questionId": 14,
      "fingerprint": "e081e7eb",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 1
    },
    {
      "questionId": 15,
      "fingerprint": "a2d8f793",
      "rationale": "Manifesto backs massive renewables, grid upgrades and interconnection, with no nuclear, CCS or LNG. This matches the all-in offshore wind and export-hub strategy best.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 49,
          "pageLabel": null,
          "text": "Deliver 9GW of onshore wind, 8GW of solar and at least 5GW of offshore wind by 2030.",
          "quoteSha": "07d66b5f12370d3c"
        },
        {
          "document": "ff-ge2024",
          "page": 49,
          "pageLabel": null,
          "text": "Complete vital energy connectivity projects, including the Celtic Interconnector.",
          "quoteSha": "8102e9d0f14a4338"
        }
      ]
    },
    {
      "questionId": 16,
      "fingerprint": "25dadce4",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 3
    },
    {
      "questionId": 17,
      "fingerprint": "471a3337",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 18,
      "fingerprint": "edec1d4e",
      "rationale": "The manifesto backs new Garda powers to disperse groups and protect public spaces from disruptive conduct, matching answer 0's swift restoration of normal operations over facilitation or dialogue-first approaches.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 113,
          "pageLabel": null,
          "text": "Introduce Dispersal Orders allowing Gardaí to disperse groups involved in anti-social activities.",
          "quoteSha": "42d5c21464df860f"
        },
        {
          "document": "ff-ge2024",
          "page": 113,
          "pageLabel": null,
          "text": "Implement Public Space Protection Orders to protect public spaces from anti-social behaviour.",
          "quoteSha": "83e36ab0c0f8c700"
        }
      ]
    },
    {
      "questionId": 19,
      "fingerprint": "7842be43",
      "rationale": "The manifesto cites its central pandemic response saving lives and proposes a new national agency for pandemic threats, indicating a centralised state-led public health approach rather than voluntary, local or targeted-only options.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 53,
          "pageLabel": null,
          "text": "Our management of the response to the Covid pandemic ensured that Ireland saved many lives and livelihoods.",
          "quoteSha": "fe029c9001652167"
        },
        {
          "document": "ff-ge2024",
          "page": 58,
          "pageLabel": null,
          "text": "Establish a new Emerging Health Threats Agency to strengthen Ireland’s ability to respond to emerging health and pandemic threats.",
          "quoteSha": "0a837643a3001be8"
        }
      ]
    },
    {
      "questionId": 20,
      "fingerprint": "f62bbcbf",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 2
    },
    {
      "questionId": 21,
      "fingerprint": "1609def7",
      "rationale": "The manifesto backs rent tax credit increases and reviews RPZ caps rather than extending them, plus ramping public housing supply, matching answer 1 over extending caps or deregulating.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 35,
          "pageLabel": null,
          "text": "Continue to review the effectiveness of the Rent Pressure Zones.",
          "quoteSha": "a237a231b45ae1e7"
        },
        {
          "document": "ff-ge2024",
          "page": 35,
          "pageLabel": null,
          "text": "Progressively double the rent tax credit.",
          "quoteSha": "a7dc83b1138bf6ba"
        }
      ]
    },
    {
      "questionId": 22,
      "fingerprint": "e1fb2ebb",
      "rationale": "The manifesto proposes direct exchequer-funded national programmes and infrastructure investment for rural towns, matching answer 0 rather than performance metrics, enterprise zones, or relocation incentives.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 144,
          "pageLabel": null,
          "text": "Establish a Rural Communities Initiative to bring together all state agencies to implement community development and town-centre rejuvenation.",
          "quoteSha": "572df0d974238f51"
        },
        {
          "document": "ff-ge2024",
          "page": 144,
          "pageLabel": null,
          "text": "Establish a new Towns Investment Fund of €2bn to build and upgrade infrastructure to support the communities living in our towns and the businesses operating there.",
          "quoteSha": "95c718be93c9969b"
        }
      ]
    },
    {
      "questionId": 23,
      "fingerprint": "3ec07b23",
      "rationale": "The manifesto endorses adopting AI and using it to improve public services, matching answer 0's embrace of AI tools for policy delivery. It does not require citizens' assemblies or restrict AI to advisory-only roles.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 187,
          "pageLabel": null,
          "text": "Refresh Ireland’s National AI Straegy and implement the new regulations including the EU AI Act that will focus on three areas:",
          "quoteSha": "cece1fed7cb62fa6"
        },
        {
          "document": "ff-ge2024",
          "page": 187,
          "pageLabel": null,
          "text": "Leveraging AI for societal and economic benefit including supporting businesses to adopt AI and harnessing AI for better public services,",
          "quoteSha": "426d8cf7dc1e3dd2"
        }
      ]
    },
    {
      "questionId": 24,
      "fingerprint": "c06f1dff",
      "rationale": "The manifesto does not address citizens' assemblies or whether their recommendations should be binding, advisory, limited, or subject to Dáil ratification.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 25,
      "fingerprint": "07c9b0b9",
      "rationale": "The manifesto's productivity reforms centre on digital transformation and technology-driven efficiency, matching answer 1. It proposes no performance bonuses, agency mergers, or devolved discretion as the leading reform.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 181,
          "pageLabel": null,
          "text": "Implement the digital transformation of parliament, in line with the digital-first principles as contained in ‘Connecting Government 2030’.",
          "quoteSha": "6be241842289fb9a"
        },
        {
          "document": "ff-ge2024",
          "page": 61,
          "pageLabel": null,
          "text": "Develop an overarching AI in Health strategy to ensure that the Irish health service harnesses the transformative potential of AI to improve the quality of care and to drive efficiency.",
          "quoteSha": "0ca30f4d3da69688"
        }
      ]
    },
    {
      "questionId": 27,
      "fingerprint": "3ab3cc9b",
      "rationale": "The manifesto addresses palliative care and end-of-life services but never mentions assisted dying, euthanasia, or any position on legislating it. No passage matches any of the four answers.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 28,
      "fingerprint": "fab89ead",
      "rationale": "The manifesto backs the Land Development Agency on public land to accelerate delivery, with private builders constructing, matching answer 1 rather than a state builder or reliance on private developers alone.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 32,
          "pageLabel": null,
          "text": "Fully capitalise the Land Development Agency out to 2030, and increase its target, enabling it to accelerate home delivery.",
          "quoteSha": "ac7f11e4a82c069c"
        },
        {
          "document": "ff-ge2024",
          "page": 29,
          "pageLabel": null,
          "text": "An allocation of €4 billion will be made available to the Land Development Agency to boost the delivery of social and affordable homes",
          "quoteSha": "ceab5e8d26d6d7bf"
        }
      ]
    },
    {
      "questionId": 29,
      "fingerprint": "3a36420a",
      "rationale": "The manifesto addresses abortion only indirectly, via a commitment to a clinically based gender healthcare service; it never discusses waiting periods or consultation timing for abortion.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 30,
      "fingerprint": "429bf7e6",
      "rationale": "The manifesto addresses school patronage only indirectly, via curriculum and Irish-language provisions, and never states a position on Catholic patronage or divestment. No passage matches any answer.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 31,
      "fingerprint": "d25e0921",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.4,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 1,
      "stale": true
    },
    {
      "questionId": 32,
      "fingerprint": "6ac7c9a0",
      "rationale": "The manifesto addresses public service broadcasting and RTÉ funding but never mentions the Angelus or any daily religious broadcast, so no position on this question is stated.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 33,
      "fingerprint": "4e33e0ca",
      "rationale": "The manifesto addresses Irish-language education but never states whether Irish should remain compulsory to the Leaving Certificate, nor proposes making it optional or teaching more subjects through Irish.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "no_preference",
      "quotes": []
    },
    {
      "questionId": 34,
      "fingerprint": "7f8a2d2c",
      "rationale": "The manifesto does not address the naming of streets, bridges or public spaces, nor whose stories such names should reflect.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 35,
      "fingerprint": "2d90c7e8",
      "rationale": "Manifesto pledges compulsory age verification for all internet users via digital ID, matching answer 0's requirement of age checks for every user; no parental-consent alternative is offered.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 76,
          "pageLabel": null,
          "text": "Introduce new legislation requiring online service providers to verify users’ age.",
          "quoteSha": "609f69055fe1fb41"
        },
        {
          "document": "ff-ge2024",
          "page": 76,
          "pageLabel": null,
          "text": "Legislate for a new online Digital Passport and require internet users to verify their age using these electronic IDs.",
          "quoteSha": "46cd5b2657cd7e76"
        }
      ]
    },
    {
      "questionId": 36,
      "fingerprint": "fc63dfdb",
      "rationale": "The manifesto commits to expanding the non-jury Special Criminal Court's remit to more organised-crime cases, matching answer 0 rather than limiting or phasing out such courts.",
      "modelConfidence": 0.85,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 114,
          "pageLabel": null,
          "text": "Expand the Remit of the Special Criminal Court to ensure that organised crime groups engaged in drug trafficking are prosecuted in the Special Criminal Court.",
          "quoteSha": "f0a02757b3e7dc43"
        }
      ]
    },
    {
      "questionId": 37,
      "fingerprint": "37d5e83d",
      "rationale": "The manifesto addresses Garda powers on body cameras, facial recognition, and anti-social behaviour, but never discusses stop-and-search thresholds or suspicion requirements.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 38,
      "fingerprint": "e90d2e5d",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 2
    },
    {
      "questionId": 39,
      "fingerprint": "206cd4cf",
      "rationale": "The manifesto commits only to following through on existing carbon tax commitments, matching the legislated path rather than accelerating, pausing, or freezing it.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 48,
          "pageLabel": null,
          "text": "Follow through on our commitments regarding carbon tax to ensure that carbon efficient practices are rewarded and to fund continued investment in environmental practices.",
          "quoteSha": "254202ced55041d6"
        }
      ]
    },
    {
      "questionId": 40,
      "fingerprint": "90aed241",
      "rationale": "The manifesto only proposes a pilot to encourage switching and a phase-out in new builds, not a firm ban date or a replacement requirement for existing homes. This matches keeping boilers allowed with grants to encourage change.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 46,
          "pageLabel": null,
          "text": "Introduce a Boiler Scrappage Pilot to encourage households to switch to more renewable sources of home energy.",
          "quoteSha": "064901ad58d98756"
        },
        {
          "document": "ff-ge2024",
          "page": 46,
          "pageLabel": null,
          "text": "Accelerate the phase-out fossil fuel boilers in new builds.",
          "quoteSha": "15fb9d887e46f406"
        }
      ]
    },
    {
      "questionId": 41,
      "fingerprint": "7105e74f",
      "rationale": "The manifesto commits to maintaining the retirement age at 66, matching answer 1 (keep it at 66) and rejecting any increase.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 88,
          "pageLabel": null,
          "text": "Increase the State pension to at least €350 per week and maintain the retirement age at 66.",
          "quoteSha": "5da464bd8a5d4d90"
        }
      ]
    },
    {
      "questionId": 42,
      "fingerprint": "00dc0e15",
      "rationale": "The manifesto caps fees at €200 per month for all families via the subsidy, matching answer 1 (low cap for every family) rather than free care, targeted-only support, or tax relief.",
      "modelConfidence": 0.8,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 72,
          "pageLabel": null,
          "text": "Increase the National Childcare Subsidy reducing parents’ fees to €200 per month, going further should economic and fiscal circumstances permit.",
          "quoteSha": "de10474c373964db"
        }
      ]
    },
    {
      "questionId": 43,
      "fingerprint": "f906fd37",
      "rationale": "The manifesto cites the Pay-Related Benefit Scheme as a landmark reform protecting people from a 'cliff-edge' after job loss, indicating support for earnings-linked payments rather than flat rates or shortening them.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 88,
          "pageLabel": null,
          "text": "we also introduced a landmark reform, a Pay-Related Benefit Scheme, which will protect people from a ‘cliff-edge’ for a period of time when they lose their job",
          "quoteSha": "0dfd1f92c828b641"
        }
      ]
    },
    {
      "questionId": 44,
      "fingerprint": "396fad74",
      "rationale": "The manifesto backs open trade and market access for Irish exporters, matching answer 0's emphasis on free trade and export markets, with no protectionist or slow-down stance.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 150,
          "pageLabel": null,
          "text": "Promote international trade, vital to the Irish economy.",
          "quoteSha": "de952436a001ca8d"
        },
        {
          "document": "ff-ge2024",
          "page": 11,
          "pageLabel": null,
          "text": "Supporting international trade, reducing costs of exporting and securing access to international markets for Irish businesses.",
          "quoteSha": "64554b5f8800bcd1"
        }
      ]
    },
    {
      "questionId": 45,
      "fingerprint": "14dff138",
      "rationale": "The manifesto commits to annual increases in aid, matching a gradual, step-by-step approach rather than reaching 0.7% quickly, holding level, or cutting aid.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ff-ge2024",
          "page": 152,
          "pageLabel": null,
          "text": "Continue to increase Official Development Assistance annually.",
          "quoteSha": "3103f08408b25ac2"
        }
      ]
    },
    {
      "questionId": 46,
      "fingerprint": "0dbe2725",
      "rationale": "The manifesto supports a stronger, reformed EU and treaty changes but never addresses unanimity, vetoes, or majority voting on foreign policy or tax.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 47,
      "fingerprint": "6bdbf910",
      "rationale": "The manifesto addresses Dáil and Seanad reform but never discusses appointing ministers from outside the Oireachtas or changing the requirement that ministers be members of the Dáil or Seanad.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 48,
      "fingerprint": "afb38ef2",
      "rationale": "The manifesto addresses referendums only in the context of future constitutional arrangements on Irish unity, not citizens' initiatives. It does not state a position on whether citizens should be able to trigger a referendum.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 49,
      "fingerprint": "16abd67c",
      "rationale": "The manifesto discusses housing supply, planning, and Central Bank-related bodies like the CRU, but never addresses who should set mortgage lending limits or macroprudential rules.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    }
  ]
};
