// Generated by `npm run party-quiz`; edit fields only; comments are not kept.
import type { PartyQuizSheet } from '@shared/partyQuiz';

export const sheet: PartyQuizSheet = {
  "party": "Fine Gael",
  "election": "ge2024",
  "documents": [
    "fg-ge2024"
  ],
  "model": "deepseek-flash",
  "promptVersion": "v2",
  "items": [
    {
      "questionId": 1,
      "fingerprint": "1ef56c01",
      "rationale": "The manifesto commits windfall funds to infrastructure, especially housing, and pledges record capital spending, matching answer 0 over tax relief, social supports, or reserving the funds.",
      "modelConfidence": 0.8,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 109,
          "pageLabel": null,
          "text": "Fine Gael will utilise the Apple tax windfall to address critical infrastructure needs, allocating over half of the proceeds to housing.",
          "quoteSha": "6aed4ab111fd47c1"
        },
        {
          "document": "fg-ge2024",
          "page": 109,
          "pageLabel": null,
          "text": "Inject €100 billion in capital projects: We will increase capital spending by 11% per year, in recognition of the crucial infrastructural investment needed in housing, water, energy and other areas.",
          "quoteSha": "6d36bced7de2bb37"
        }
      ]
    },
    {
      "questionId": 2,
      "fingerprint": "d9a4ede8",
      "rationale": "The manifesto commits to defending the corporate tax regime against harmonisation and indirect changes, and to keeping tax policy sovereign, matching answer 0 over complying with EU minimum rates or raising rates.",
      "modelConfidence": 0.8,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 113,
          "pageLabel": null,
          "text": "Defend Ireland’s Corporate Tax regime: We will strongly protect our corporate tax framework from attempts at harmonisation or indirect changes.",
          "quoteSha": "461d633a330622c3"
        }
      ]
    },
    {
      "questionId": 3,
      "fingerprint": "ef513b0e",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 1
    },
    {
      "questionId": 4,
      "fingerprint": "559f8cbf",
      "rationale": "Manifesto favours targeted support for vulnerable households and energy-cost grants for businesses, not universal price caps or market-only approaches, matching answer 1.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 46,
          "pageLabel": null,
          "text": "Reinvest Carbon Tax Revenue in Vulnerable Households: Use revenue from the carbon tax to fund social welfare measures that support the most vulnerable",
          "quoteSha": "c8e9119522441b7a"
        },
        {
          "document": "fg-ge2024",
          "page": 101,
          "pageLabel": null,
          "text": "Energy Cost Grant Scheme: We will establish a new grant scheme to help businesses lower their energy costs",
          "quoteSha": "b29adc94ba480f14"
        }
      ]
    },
    {
      "questionId": 5,
      "fingerprint": "bb8e1c30",
      "rationale": "The manifesto backs parental choice including faith-based schools, and elsewhere promises an inclusive education model and a Citizens' Assembly on inclusive education, matching a blend of pluralism with continuity rather than a purely rights-focused or practical-only curriculum.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 13,
          "pageLabel": null,
          "text": "Fine Gael is committed to enhancing parental choice in education, ensuring that families can access both denominational and faith-based schools.",
          "quoteSha": "586f3c91a4000ce0"
        }
      ]
    },
    {
      "questionId": 6,
      "fingerprint": "a3c40286",
      "rationale": "Manifesto backs Sláintecare's mixed public/private model with universal access, not full state-run, insurance mandate, or vouchers. It commits to public capacity and reduced costs within existing system, matching answer 1.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 80,
          "pageLabel": null,
          "text": "Sláintecare is a comprehensive roadmap designed to strengthen Ireland’s health system.",
          "quoteSha": "5f93f6902dc3a91e"
        },
        {
          "document": "fg-ge2024",
          "page": 80,
          "pageLabel": null,
          "text": "Developed through consensus with other parties, and actioned by Simon Harris, it aims to ensure that everyone can access the care they need.",
          "quoteSha": "b91e0737d384dd4f"
        }
      ]
    },
    {
      "questionId": 7,
      "fingerprint": "7a9221d8",
      "rationale": "The manifesto addresses reproductive rights only by committing to full termination services under the 2018 Act, and does not discuss a personal freedoms bill, speech, assembly, or conscience clauses.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 8,
      "fingerprint": "f7fb5915",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.2,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 2
    },
    {
      "questionId": 9,
      "fingerprint": "21820e1a",
      "rationale": "The manifesto backs converting and refurbishing existing buildings, including commercial-to-residential conversions, rather than demolition or relocation, matching adaptive reuse while retaining existing structures.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 26,
          "pageLabel": null,
          "text": "Supporting Conversions and Vacant Properties: Maintain the Vacant Property Refurbishment Grant, provide additional Vacant Home Officers, and make it easier for authorities to acquire vacant properties.",
          "quoteSha": "afdc51b31aa1c80f"
        },
        {
          "document": "fg-ge2024",
          "page": 26,
          "pageLabel": null,
          "text": "Promoting “Over the Shop” Living: Fund demonstration projects to showcase successful conversions and extend planning exemptions for commercial-to-residential conversions until 2030.",
          "quoteSha": "0840099d9d4c684c"
        }
      ]
    },
    {
      "questionId": 10,
      "fingerprint": "308af8e2",
      "rationale": "The manifesto rejects cuts, pledging to maintain and grow arts funding and support artists and cultural spaces, which aligns with prioritising community arts and emerging voices over scaling back state involvement.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 49,
          "pageLabel": null,
          "text": "We have doubled arts funding from 2018 to 2025, reinforcing our commitment to integrating culture and creativity into every child’s education and to supporting artists and cultural spaces.",
          "quoteSha": "922516f7b9453a67"
        },
        {
          "document": "fg-ge2024",
          "page": 49,
          "pageLabel": null,
          "text": "Sustain Funding for the Arts: Maintain and grow funding for the Arts Council, Culture Ireland, and other organisations that support both national and international artistic endeavours.",
          "quoteSha": "c73745a4b146822e"
        }
      ]
    },
    {
      "questionId": 11,
      "fingerprint": "cb14689e",
      "rationale": "The manifesto preserves military neutrality while deepening cooperation with the EU and NATO on peacekeeping, cyber and procurement, matching answer 1 rather than full combat integration or declining cooperation.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 71,
          "pageLabel": null,
          "text": "Preserve Ireland’s policy of active military neutrality: We recognise that while we maintain military neutrality, we are not politically neutral and will engage with international partners when necessary.",
          "quoteSha": "35c4c929981e4195"
        },
        {
          "document": "fg-ge2024",
          "page": 71,
          "pageLabel": null,
          "text": "Support active military cooperation: We will enhance cooperation between our Defence Forces and international partners, including the United Nations, European Union, and NATO, focusing on: International security and peacekeeping",
          "quoteSha": "6d2a64b7c9140ef7"
        }
      ]
    },
    {
      "questionId": 12,
      "fingerprint": "dc35f0f4",
      "rationale": "Fine Gael broadly engages with EU CAP reform but seeks recognition of Irish agriculture's unique circumstances, matching answer 1's integration-with-carve-outs position rather than full harmonisation or opposition.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 96,
          "pageLabel": null,
          "text": "We will simplify schemes to deliver the best outcomes for farmers, consumers, and the environment",
          "quoteSha": "da1d739792969a33"
        },
        {
          "document": "fg-ge2024",
          "page": 97,
          "pageLabel": null,
          "text": "We will advocate for Ireland’s unique circumstances through the European People’s Party.",
          "quoteSha": "b43699baa53c7a3a"
        }
      ]
    },
    {
      "questionId": 13,
      "fingerprint": "a7b1e486",
      "rationale": "The manifesto commits to accommodating protection applicants on State land and phasing new facilities with lead-in time and integration, matching gradual, milestone-based capacity rather than immediate expansion or refusal.",
      "modelConfidence": 0.62,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 66,
          "pageLabel": null,
          "text": "We will move away from the emergency use of hotels for housing asylum seekers and put in place facilities for those seeking protection on state land.",
          "quoteSha": "18e094bd0b87124d"
        },
        {
          "document": "fg-ge2024",
          "page": 67,
          "pageLabel": null,
          "text": "Give greater lead-in time to the opening of new facilities, allowing for enhanced and effective local communication, and development of integration.",
          "quoteSha": "bb62e61a5895ac28"
        }
      ]
    },
    {
      "questionId": 14,
      "fingerprint": "e081e7eb",
      "rationale": "The manifesto backs farmers reducing emissions through existing progress and biogenic methane recognition, with no herd reduction, offset credits, or relaxed timelines; it favours practical supports and innovation over mandating cuts.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 98,
          "pageLabel": null,
          "text": "Recognising the special economic and social role of agriculture and the distinct characteristics of biogenic methane, support the progress made to date by agriculture in reducing emissions.",
          "quoteSha": "33037aeb8950b0e9"
        }
      ]
    },
    {
      "questionId": 15,
      "fingerprint": "a2d8f793",
      "rationale": "Manifesto backs renewables, offshore wind and becoming a net energy exporter, matching answer 0; it rejects nuclear, CCS and LNG options.",
      "modelConfidence": 0.8,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 42,
          "pageLabel": null,
          "text": "Fine Gael envisions Ireland as energy-independent and a net energy exporter by 2040.",
          "quoteSha": "f384707eb57a8e86"
        },
        {
          "document": "fg-ge2024",
          "page": 43,
          "pageLabel": null,
          "text": "Fast-Track Offshore Wind Development: Prioritise the publication of Designated Maritime Area Plans (DMAPs) and increase resources for responsible agencies to accelerate offshore wind projects.",
          "quoteSha": "c9ae2a11ced9c4ea"
        }
      ]
    },
    {
      "questionId": 16,
      "fingerprint": "25dadce4",
      "rationale": "The manifesto prioritises delivering major public transport projects like DART+ and MetroLink before any congestion charge, matching answer 1's phase-in after commuter rail expansions. It never proposes a congestion charge.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 38,
          "pageLabel": null,
          "text": "Build Major Public Transport Projects: Prioritise the delivery of Bus Connects, MetroLink, Luas Finglas, the DART+ Programme, and the Cork Commuter Rail Programme to improve urban connectivity and convenience.",
          "quoteSha": "e09c05d9d05388b8"
        }
      ]
    },
    {
      "questionId": 17,
      "fingerprint": "471a3337",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.75,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 18,
      "fingerprint": "edec1d4e",
      "rationale": "Manifesto pledges stronger public order powers and protest restrictions, indicating a firm response to disruptive protests rather than facilitation or non-intervention.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 61,
          "pageLabel": null,
          "text": "Ban Intimidating Masks at Protests: Ban the wearing of masks at protests intended to intimidate others and implement a ban on protests outside private homes.",
          "quoteSha": "06f2712d3a16184a"
        },
        {
          "document": "fg-ge2024",
          "page": 61,
          "pageLabel": null,
          "text": "Strengthen Public Order Acts: Review and update Public Order Acts to give Gardaí the power they need to manage public order situations effectively.",
          "quoteSha": "6244b851377b22e0"
        }
      ]
    },
    {
      "questionId": 19,
      "fingerprint": "7842be43",
      "rationale": "The manifesto does not address pandemic response approaches, mandatory restrictions, voluntary guidance, local tailoring, or high-risk group protection.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 20,
      "fingerprint": "f62bbcbf",
      "rationale": "The manifesto rejects blanket universal payments, prioritising work over welfare and targeted supports, matching answer 3 over UBI adoption, pilots, or expanded targeted-only programmes.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 3,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 93,
          "pageLabel": null,
          "text": "Fine Gael believes that work should always pay, and nobody should be better off on social welfare than in a job.",
          "quoteSha": "0b0f6495b8a334ee"
        }
      ]
    },
    {
      "questionId": 21,
      "fingerprint": "1609def7",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 1
    },
    {
      "questionId": 22,
      "fingerprint": "e1fb2ebb",
      "rationale": "The manifesto commits central exchequer funds and national programmes (URDF, Rural Regeneration Fund, broadband, Connected Hubs) to lift regional services and jobs directly, matching answer 0 over performance-tied, enterprise-zone or relocation approaches.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 33,
          "pageLabel": null,
          "text": "Re-launch the Urban Regeneration and Development Fund (URDF): Provide a new capital injection to regenerate Ireland’s five cities and other large towns.",
          "quoteSha": "790bbd27018278f4"
        },
        {
          "document": "fg-ge2024",
          "page": 35,
          "pageLabel": null,
          "text": "Increase the Rural Regeneration and Development Fund to a total of €2 billion out to 2035: The Fund will focus on projects which support rural job creation and infrastructure improvements in rural towns.",
          "quoteSha": "3279b44ad1b93cbc"
        }
      ]
    },
    {
      "questionId": 23,
      "fingerprint": "3ec07b23",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 24,
      "fingerprint": "c06f1dff",
      "rationale": "The manifesto commits only to holding a Citizens' Assembly to consider issues; it does not state whether such assemblies should gain binding authority, nor how their recommendations would be treated.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "no_preference",
      "quotes": []
    },
    {
      "questionId": 25,
      "fingerprint": "07c9b0b9",
      "rationale": "The manifesto's public service reform approach centres on digital transformation and user-centric redesign, not performance bonuses, agency mergers, or devolving control to front-line units.",
      "modelConfidence": 0.8,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 114,
          "pageLabel": null,
          "text": "Redesigning services: We will apply the latest technologies and encourage joined-up thinking to guarantee high-quality service delivery, maximising the potential benefits of AI.",
          "quoteSha": "f174f8af5ec0b013"
        }
      ]
    },
    {
      "questionId": 27,
      "fingerprint": "3ab3cc9b",
      "rationale": "The manifesto addresses palliative care and end-of-life services but never mentions assisted dying, euthanasia, or any proposal to legislate for it, so no position on the question is stated.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 28,
      "fingerprint": "fab89ead",
      "rationale": "The manifesto backs the Land Development Agency unlocking public land for housing, with private builders delivering, matching answer 1 rather than a state builder or private developers alone.",
      "modelConfidence": 0.75,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 26,
          "pageLabel": null,
          "text": "Fine Gael established the LDA to develop state-owned land for housing.",
          "quoteSha": "a7d2468930846d0c"
        },
        {
          "document": "fg-ge2024",
          "page": 27,
          "pageLabel": null,
          "text": "Support the LDA in unlocking state land for housing, including Project Tosaigh, targeting land with unused planning permission.",
          "quoteSha": "e70cc9dbb9fda0d8"
        }
      ]
    },
    {
      "questionId": 29,
      "fingerprint": "3a36420a",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 30,
      "fingerprint": "429bf7e6",
      "rationale": "The manifesto commits to enhancing parental choice and ensuring access to both denominational and faith-based schools, indicating support for widening options rather than transferring existing Catholic schools on a national timetable.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 13,
          "pageLabel": null,
          "text": "Fine Gael is committed to enhancing parental choice in education, ensuring that families can access both denominational and faith-based schools.",
          "quoteSha": "586f3c91a4000ce0"
        }
      ]
    },
    {
      "questionId": 31,
      "fingerprint": "095134aa",
      "rationale": "The manifesto commits to introducing surrogacy leave, indicating support for allowing surrogacy, but it never states whether payment beyond expenses is permitted or restricts it to Ireland, so it does not choose among the answers.",
      "modelConfidence": 0.3,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "no_preference",
      "quotes": []
    },
    {
      "questionId": 32,
      "fingerprint": "6ac7c9a0",
      "rationale": "The manifesto does not mention the Angelus, RTÉ's daily religious broadcast, or any policy on broadcasting a religious devotion, so no position can be drawn from the documents.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 33,
      "fingerprint": "4e33e0ca",
      "rationale": "The manifesto proposes reforming Leaving Cert Irish but does not state whether Irish should remain compulsory, become optional, or be taught more widely, so it does not choose between the answers.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "no_preference",
      "quotes": []
    },
    {
      "questionId": 34,
      "fingerprint": "7f8a2d2c",
      "rationale": "The manifesto does not address the naming of streets, bridges or public spaces, nor whose stories such names should tell.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 35,
      "fingerprint": "2d90c7e8",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 2
    },
    {
      "questionId": 36,
      "fingerprint": "fc63dfdb",
      "rationale": "The manifesto commits to retaining the juryless Special Criminal Court for organised crime and terrorism, matching answer 0's call to keep and extend non-jury courts.",
      "modelConfidence": 0.8,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 63,
          "pageLabel": null,
          "text": "Retain the Special Criminal Court: This court will remain a vital tool in our fight against organised crime, terrorism, and paramilitary activity",
          "quoteSha": "84e477368170e4c8"
        }
      ]
    },
    {
      "questionId": 37,
      "fingerprint": "37d5e83d",
      "rationale": "The manifesto only proposes expanding search powers over digital devices when a warrant is already served; it does not address stop-and-search without reasonable suspicion, so no answer is matched.",
      "modelConfidence": 0.8,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 38,
      "fingerprint": "e90d2e5d",
      "rationale": "The manifesto permits data centres that contribute to growth and efficient grid usage, but does not require new renewable supply or pause connections, nor prioritise them over others.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "no_preference",
      "quotes": []
    },
    {
      "questionId": 39,
      "fingerprint": "206cd4cf",
      "rationale": "The manifesto commits to continuing the planned annual carbon tax increases to €100 per tonne by 2030, matching answer 1 rather than faster, paused, or frozen/cut options.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 46,
          "pageLabel": null,
          "text": "Stay on Track to €100 per Tonne by 2030: Continue with the planned carbon tax increase to reach €100 per tonne of CO₂ by 2030",
          "quoteSha": "185bbd06d9ca794e"
        }
      ]
    },
    {
      "questionId": 40,
      "fingerprint": "90aed241",
      "rationale": "The manifesto targets existing oil-heated homes to switch to renewable heating, but offers grants and support rather than a ban or mandatory replacement, matching answer 2's voluntary approach.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 44,
          "pageLabel": null,
          "text": "Support Transition from Oil and Fossil Fuels: Target older homes still using oil to switch to renewable heating systems, lowering carbon footprints and costs.",
          "quoteSha": "e4d15feae568a4cb"
        }
      ]
    },
    {
      "questionId": 41,
      "fingerprint": "7105e74f",
      "rationale": "The manifesto keeps the pension age at 66, retaining the 65-year-old benefit payment until pension age at 66, matching answer 1 rather than lowering or raising the age.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 94,
          "pageLabel": null,
          "text": "Retain the Benefit Payment for 65-year-olds: Continue this payment for workers retiring at 65 until they reach pension age at 66, with no requirement to sign on.",
          "quoteSha": "24802981efebb9e7"
        }
      ]
    },
    {
      "questionId": 42,
      "fingerprint": "00dc0e15",
      "rationale": "Manifesto caps fees at €200/month per child for all families, and states lower-income families benefit more, matching answer 1 over free universal care, means-tested-only support, or tax relief.",
      "modelConfidence": 0.85,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 8,
          "pageLabel": null,
          "text": "Cap Childcare Costs: We’ll limit childcare costs to €200 per month per child, or €600 for a family with more than 3 children.",
          "quoteSha": "555ece4b4fb4e632"
        },
        {
          "document": "fg-ge2024",
          "page": 9,
          "pageLabel": null,
          "text": "Lower income families will benefit more from its inception",
          "quoteSha": "547242bddd5762c1"
        }
      ]
    },
    {
      "questionId": 43,
      "fingerprint": "f906fd37",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.2,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 1
    },
    {
      "questionId": 44,
      "fingerprint": "396fad74",
      "rationale": "Supports continued free trade deals but with binding protections for agriculture and standards, matching answer 1 rather than open-markets-only or shielding/slowing deals.",
      "modelConfidence": 0.8,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 106,
          "pageLabel": null,
          "text": "Promote new Free Trade Agreements: Our economy is based on the ability to trade internationally. We will ensure these agreements include proper assurances regarding sustainability, human rights and the protection of our agricultural sector.",
          "quoteSha": "ad05a7891651dae5"
        }
      ]
    },
    {
      "questionId": 45,
      "fingerprint": "14dff138",
      "rationale": "The manifesto commits only to working towards the 0.7% UN target, without promising to exceed it or specifying a rapid timeline, matching gradual progress better than the other answers.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "fg-ge2024",
          "page": 76,
          "pageLabel": null,
          "text": "Work towards the UN target of 0.7% of Gross National Income (GNI) for ODA",
          "quoteSha": "4bd721e9a3db5c0d"
        }
      ]
    },
    {
      "questionId": 46,
      "fingerprint": "0dbe2725",
      "rationale": "The manifesto insists Irish tax policy remains sovereign and determined in Ireland, implying opposition to majority voting on tax. It does not address vetoes on foreign policy, so no answer matches fully.",
      "modelConfidence": 0.3,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "no_preference",
      "quotes": []
    },
    {
      "questionId": 47,
      "fingerprint": "6bdbf910",
      "rationale": "The manifesto does not address whether the Taoiseach should be able to appoint outside experts as ministers; it only discusses ministerial roles and public sector staffing generally.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 48,
      "fingerprint": "afb38ef2",
      "rationale": "The manifesto discusses referendums only in passing (e.g. plebiscites for directly elected mayors) and never addresses whether citizens should be able to trigger a referendum. No position on citizens' initiative referendums is stated.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 49,
      "fingerprint": "16abd67c",
      "rationale": "The manifesto discusses mortgage arrears support and keeping Mortgage Interest Tax Relief under review, but never addresses who should set Central Bank mortgage lending limits.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    }
  ]
};
