// Generated by `npm run party-quiz`; edit fields only; comments are not kept.
import type { PartyQuizSheet } from '@shared/partyQuiz';

export const sheet: PartyQuizSheet = {
  "party": "Green Party",
  "election": "ge2024",
  "documents": [
    "greens-ge2024"
  ],
  "model": "deepseek-flash",
  "promptVersion": "v2",
  "items": [
    {
      "questionId": 1,
      "fingerprint": "1ef56c01",
      "rationale": "The manifesto identifies infrastructure deficits as the core constraint and commits surplus corporation tax receipts to funds for infrastructure and climate, matching answer 0 over tax relief, social supports or pure reserve.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 86,
          "pageLabel": "83",
          "text": "Ireland’s real economic constraint is a deficiency of basic infrastructure – housing, public transport, water and energy.",
          "quoteSha": "0b9a04ef8f59ea37"
        },
        {
          "document": "greens-ge2024",
          "page": 86,
          "pageLabel": "83",
          "text": "We will stick by our commitment to transfer excess corporation tax receipts into the new Future Ireland Fund and Infrastructure, Climate and Nature Fund",
          "quoteSha": "caad370b124e83ad"
        }
      ]
    },
    {
      "questionId": 2,
      "fingerprint": "d9a4ede8",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.4,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 2
    },
    {
      "questionId": 3,
      "fingerprint": "ef513b0e",
      "rationale": "The party proposes funding public transport from the Apple tax lump sum and the National Development Plan, i.e. exchequer sources, not private partnerships, and prioritises public transport spending.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 38,
          "pageLabel": "35",
          "text": "We propose that €7 billion of that should come from the Apple corporate tax lump sum with the remainder coming from the next revision of the National Development Plan.",
          "quoteSha": "7ffa0ef86c566a9f"
        }
      ]
    },
    {
      "questionId": 4,
      "fingerprint": "559f8cbf",
      "rationale": "The documents target support at low-income households at risk of energy poverty, not universal price caps or pure market signals, matching answer 1's targeted rebates for the most exposed.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 15,
          "pageLabel": "12",
          "text": "Provide 100% grants to low-income households at risk of energy poverty for the installation of rooftop solar panels.",
          "quoteSha": "b62500501bb8eac7"
        },
        {
          "document": "greens-ge2024",
          "page": 15,
          "pageLabel": "12",
          "text": "Update the SEAI’s mandate to focus on supporting those most at risk of energy poverty.",
          "quoteSha": "55350a0a0fb54099"
        }
      ]
    },
    {
      "questionId": 5,
      "fingerprint": "bb8e1c30",
      "rationale": "The manifesto backs inclusion programmes against racism and discrimination, plus anti-racism and Traveller/Roma inclusion strategies, matching answer 0's emphasis on rights, diversity and minority experiences over heritage, media literacy or local control.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 36,
          "pageLabel": "33",
          "text": "Introduce social cohesion and inclusion programmes in all schools to address racism and discrimination, while increasing children’s sense of belonging and cultural connection.",
          "quoteSha": "7b96a1b08a240f72"
        },
        {
          "document": "greens-ge2024",
          "page": 60,
          "pageLabel": "57",
          "text": "Continue to implement the national Anti-Racism Strategy and the recently published National Traveller and Roma Inclusion Strategy.",
          "quoteSha": "6ab0786ba287e198"
        }
      ]
    },
    {
      "questionId": 6,
      "fingerprint": "a3c40286",
      "rationale": "The manifesto backs expanding public acute capacity and the public-only consultant contract, moving toward a publicly delivered system rather than insurance, vouchers, or a capped-profit mixed model.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 75,
          "pageLabel": "72",
          "text": "Continue to roll out the public-only consultant contract.",
          "quoteSha": "26fab2e3829fda71"
        },
        {
          "document": "greens-ge2024",
          "page": 75,
          "pageLabel": "72",
          "text": "Expand capacity in acute healthcare settings by developing new elective hospitals and surgical hubs in Cork, Galway, Limerick, Waterford, and Dublin.",
          "quoteSha": "491c449fe8406ad2"
        }
      ]
    },
    {
      "questionId": 7,
      "fingerprint": "7a9221d8",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 8,
      "fingerprint": "f7fb5915",
      "rationale": "Documents address both Gaeilge and migrant integration separately, but no passage pairs Irish-language groups with migrant organisations or defines community-led cultural partnerships, so no answer is clearly preferred.",
      "modelConfidence": 0.3,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "no_preference",
      "quotes": []
    },
    {
      "questionId": 9,
      "fingerprint": "21820e1a",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "unverified_quote",
      "quotes": [],
      "rationale": "quote 2 was not found on page 8 of greens-ge2024 (not_found); copy it exactly",
      "modelConfidence": 0,
      "review": "pending"
    },
    {
      "questionId": 10,
      "fingerprint": "308af8e2",
      "rationale": "The manifesto backs direct state arts funding, expanding the Basic Income for the Arts and local creative workspaces, prioritising artists and community access rather than flagship institutions, economic-return tests, or private patronage.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 62,
          "pageLabel": "59",
          "text": "Retain and expand our flagship Basic Income for the Arts pilot programme.",
          "quoteSha": "7d5a676a939559f5"
        },
        {
          "document": "greens-ge2024",
          "page": 62,
          "pageLabel": "59",
          "text": "Support local authorities to provide more studios, practice spaces and workspaces for the creative community.",
          "quoteSha": "1a59edf2b82b816c"
        }
      ]
    },
    {
      "questionId": 11,
      "fingerprint": "cb14689e",
      "rationale": "The party supports limited, case-by-case engagement in EU defence structures only where it does not impinge on neutrality, matching answer 1's logistics/cyber/intelligence cooperation while keeping combat neutrality.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 73,
          "pageLabel": "70",
          "text": "Where it is effective and does not impinge on Ireland’s status as a neutral country, support limited continued engagement in PESCO, the European Defence Union, and other structured cooperation initiatives on a case-by-case basis.",
          "quoteSha": "6edec52313637186"
        }
      ]
    },
    {
      "questionId": 12,
      "fingerprint": "dc35f0f4",
      "rationale": "The party endorses the EU-level Strategic Dialogue and CAP reform ending area-based payments, and commits to EU climate targets, indicating support for harmonised EU agricultural policy rather than opt-outs or national control.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 48,
          "pageLabel": "45",
          "text": "The vision set out in the Strategic Dialogue is one we support, recognising that we can and must work towards a future in which it is profitable to be a farmer",
          "quoteSha": "43791997766594dc"
        },
        {
          "document": "greens-ge2024",
          "page": 49,
          "pageLabel": "46",
          "text": "Take immediate action to accelerate the measures outlined by Teagasc in its Marginal Abatement Cost Curve as being necessary to achieve the 25% emissions reduction target.",
          "quoteSha": "13769a693179a2f4"
        }
      ]
    },
    {
      "questionId": 13,
      "fingerprint": "a7b1e486",
      "rationale": "The manifesto commits to scaling accommodation and integration supports, matching answer 0's expansion of services nationwide; it does not propose phasing quotas or holding intake steady.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 68,
          "pageLabel": "65",
          "text": "We will continue to implement the Comprehensive Accommodation Strategy, delivering 14,000 state-owned beds by building on state-owned sites and purchasing large scale buildings for conversion.",
          "quoteSha": "f4f509bd8b4179bb"
        },
        {
          "document": "greens-ge2024",
          "page": 69,
          "pageLabel": "66",
          "text": "Provide integration supports from day one to all those awaiting assessment, delivered within Reception Centres.",
          "quoteSha": "90146c4c1530fb0f"
        }
      ]
    },
    {
      "questionId": 14,
      "fingerprint": "e081e7eb",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 1
    },
    {
      "questionId": 15,
      "fingerprint": "a2d8f793",
      "rationale": "Manifesto backs massive renewables plus interconnectors, and explicitly rejects commercial LNG, so answer 0 fits; answers 1-3 are excluded by silence on nuclear and opposition to LNG.",
      "modelConfidence": 0.85,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 21,
          "pageLabel": "18",
          "text": "We will deliver a zero-carbon electricity system by 2035 and develop 20GW of offshore wind, 10GW of onshore wind, and 15GW of solar by 2040.",
          "quoteSha": "d76e45ccd35d2fee"
        },
        {
          "document": "greens-ge2024",
          "page": 25,
          "pageLabel": "22",
          "text": "We will always stand firmly against the development of a commercial LNG facility in Ireland.",
          "quoteSha": "f5df01214daf7318"
        }
      ]
    },
    {
      "questionId": 16,
      "fingerprint": "25dadce4",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 17,
      "fingerprint": "471a3337",
      "rationale": "The manifesto supports facial recognition only for the most serious crimes with safeguards, matching limited high-threat use with oversight rather than broad access or outright rejection.",
      "modelConfidence": 0.8,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 59,
          "pageLabel": "56",
          "text": "Restrict the use of facial recognition technology by AGS to the detection of the most serious crimes, with appropriate safeguards in place",
          "quoteSha": "8ea62817aea2fb0b"
        }
      ]
    },
    {
      "questionId": 18,
      "fingerprint": "edec1d4e",
      "rationale": "The documents do not address protest response or blocking infrastructure; no passage states a position on clearing, facilitating, negotiating, or protecting such protests.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 19,
      "fingerprint": "7842be43",
      "rationale": "The manifesto addresses public health, health service reform and pandemic-era measures only in passing; it does not state a position on mandatory restrictions, voluntary guidance, localised responses or shielding high-risk groups for a new pandemic variant.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 20,
      "fingerprint": "f62bbcbf",
      "rationale": "The manifesto commits to guaranteeing a basic income for everyone by reforming welfare eligibility, matching answer 0's nationwide baseline income and welfare simplification.",
      "modelConfidence": 0.75,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 14,
          "pageLabel": "11",
          "text": "Reform the social welfare system so that eligibility for social assistance payments is determined by income, not by employment status, guaranteeing a basic income for everyone.",
          "quoteSha": "22460590d57c012f"
        }
      ]
    },
    {
      "questionId": 21,
      "fingerprint": "1609def7",
      "rationale": "The manifesto commits to extending rent caps and to state-backed schemes keeping at-risk tenants in their homes, matching answer 0's combination of strong protections and direct government intervention.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 9,
          "pageLabel": "6",
          "text": "Extend the Rent Pressure Zone legislation.",
          "quoteSha": "607b3793e977b23b"
        },
        {
          "document": "greens-ge2024",
          "page": 9,
          "pageLabel": "6",
          "text": "Protect renters by resourcing local authorities and AHBs to make the Tenant-in-Situ and Cost-Rental-Tenant-in-Situ schemes as effective as possible.",
          "quoteSha": "c8a7e984c1939b7b"
        }
      ]
    },
    {
      "questionId": 22,
      "fingerprint": "e1fb2ebb",
      "rationale": "The party proposes central state action: a Super-Junior Minister directing public capital to regional cities, plus national rural funds and programmes, matching answer 0 over local/private-led options.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 6,
          "pageLabel": "3",
          "text": "Appoint a powerful Super-Junior Minister for the Regional Cities, responsible for the balanced development of our country.",
          "quoteSha": "2b4e167745c693e1"
        },
        {
          "document": "greens-ge2024",
          "page": 54,
          "pageLabel": "51",
          "text": "Continue to support the Rural Development Investment Programme.",
          "quoteSha": "61745fdaca73413d"
        }
      ]
    },
    {
      "questionId": 23,
      "fingerprint": "3ec07b23",
      "rationale": "The manifesto favours participatory democracy and citizens' assemblies to validate major policy directions, matching answer 1's blend of expert input with citizen validation, rather than purely technocratic or advisory-only approaches.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 82,
          "pageLabel": "79",
          "text": "Push for less bureaucratic and more effective public consultation on new policy developments, requiring public bodies to justify their decisions to citizens.",
          "quoteSha": "3ca3399310d22bb2"
        },
        {
          "document": "greens-ge2024",
          "page": 83,
          "pageLabel": "80",
          "text": "Support an all-island Citizens’ Assembly which would both review current governance mechanisms in terms of inclusivity and fair representation and generate and refine options for new governance structures.",
          "quoteSha": "ccd8d6dd11b8640f"
        }
      ]
    },
    {
      "questionId": 24,
      "fingerprint": "c06f1dff",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 2
    },
    {
      "questionId": 25,
      "fingerprint": "07c9b0b9",
      "rationale": "The manifesto frames sluggish public services as needing major digital investment and user-centric redesign, not performance bonuses, agency mergers, or loosened central controls.",
      "modelConfidence": 0.82,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 74,
          "pageLabel": "71",
          "text": "A core element of our approach to optimising access and efficiency is significant investment in modern technology.",
          "quoteSha": "4969eda725248884"
        },
        {
          "document": "greens-ge2024",
          "page": 83,
          "pageLabel": "80",
          "text": "Our ambition is to deliver convenient services that are accessible to everyone regardless of their digital skills",
          "quoteSha": "26acf858596e98e6"
        }
      ]
    },
    {
      "questionId": 27,
      "fingerprint": "3ab3cc9b",
      "rationale": "The manifesto commits to legislating for assisted dying, limited to terminally ill, mentally competent adults with strict legal safeguards, matching answer 0 rather than a citizens' assembly, palliative-first delay, or maintaining the ban.",
      "modelConfidence": 0.85,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 79,
          "pageLabel": "76",
          "text": "We will introduce legislation which allows for assisted dying in Ireland, based on the recommendations of the Oireachtas Committee on Assisted Dying.",
          "quoteSha": "b0c0ea476fae5d03"
        }
      ]
    },
    {
      "questionId": 28,
      "fingerprint": "fab89ead",
      "rationale": "The party backs delivery through the Land Development Agency and public bodies while keeping private development finance involved, matching answer 1 rather than a new state construction company or private developers alone.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 6,
          "pageLabel": "3",
          "text": "Deliver affordable and cost rental housing via local authorities, Approved Housing Bodies (AHBs), and the Land Development Agency in every part of the country",
          "quoteSha": "c5ebf3656e20f663"
        },
        {
          "document": "greens-ge2024",
          "page": 10,
          "pageLabel": "7",
          "text": "It is important that we don’t shut the door on private development finance.",
          "quoteSha": "6fc92c895aabb85d"
        }
      ]
    },
    {
      "questionId": 29,
      "fingerprint": "3a36420a",
      "rationale": "The manifesto commits to removing the existing three-day waiting period, matching answer 0's call to drop any mandatory wait.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 76,
          "pageLabel": "73",
          "text": "Remove the obligatory three-day waiting period before termination medication can be prescribed.",
          "quoteSha": "b5065b1ece4358c8"
        }
      ]
    },
    {
      "questionId": 30,
      "fingerprint": "429bf7e6",
      "rationale": "The manifesto commits to increasing multi-denominational schools and reforming the transfer process, indicating support for moving schools away from Catholic patronage, though it does not specify a firm national timetable.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 35,
          "pageLabel": "32",
          "text": "Increase the number of multi-denominational schools and Gaelcholáistí. Reform and revitalise the process of transferring viable schools to Community National Schools.",
          "quoteSha": "c8f9a46355e9152c"
        }
      ]
    },
    {
      "questionId": 31,
      "fingerprint": "d25e0921",
      "rationale": "The documents do not address surrogacy or how Irish law should treat it.",
      "modelConfidence": 1,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 32,
      "fingerprint": "6ac7c9a0",
      "rationale": "The documents do not mention the Angelus, RTÉ's daily religious broadcast, or any position on retaining, replacing or removing it.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 33,
      "fingerprint": "4e33e0ca",
      "rationale": "The manifesto commits to doubling students learning through Irish, matching answer 3's aim of teaching more subjects through Irish; it does not propose making Irish optional or merely widening exemptions.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 3,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 36,
          "pageLabel": "33",
          "text": "Publish, as a priority, a separate policy for the Irish language in the education system to bring teaching in line with the Common European Framework of Reference for Languages (CEFR), and to double the number of students learning through Irish.",
          "quoteSha": "04b7f1f2bb8372e3"
        }
      ]
    },
    {
      "questionId": 34,
      "fingerprint": "7f8a2d2c",
      "rationale": "The manifesto addresses commemorative naming only for a National Women's Museum, not for streets, bridges or public spaces, and states no position on whose stories such names should tell.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 35,
      "fingerprint": "2d90c7e8",
      "rationale": "The manifesto addresses online child protection but only promises agile law updates under the Online Safety and Media Regulation Act; it never mentions age verification, parental consent, or banning under-16s, so it does not choose among the answers.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "no_preference",
      "quotes": []
    },
    {
      "questionId": 36,
      "fingerprint": "fc63dfdb",
      "rationale": "The documents discuss courts, Gardaí, and justice modernisation but never address non-jury or Special Criminal Court trials for terrorism or gangland cases.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 37,
      "fingerprint": "37d5e83d",
      "rationale": "The documents discuss Garda reform, facial recognition limits and justice modernisation, but never address stop-and-search powers or reasonable suspicion. No position on changing search powers is stated.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 38,
      "fingerprint": "e90d2e5d",
      "rationale": "The manifesto conditions support for new data centres on being 100% carbon neutral, do not threaten supply, and do not overwhelm the grid, matching answer 1's requirement that new demand come with clean supply.",
      "modelConfidence": 0.8,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 22,
          "pageLabel": "19",
          "text": "We will only support the development of new data centres if developers can demonstrate that they can be 100% carbon neutral",
          "quoteSha": "2304d26ea4e32ef5"
        }
      ]
    },
    {
      "questionId": 39,
      "fingerprint": "206cd4cf",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "unverified_quote",
      "quotes": [],
      "rationale": "quote 1 was not found on page 23 of greens-ge2024 (not_found); copy it exactly",
      "modelConfidence": 0,
      "review": "pending"
    },
    {
      "questionId": 40,
      "fingerprint": "90aed241",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "unverified_quote",
      "quotes": [],
      "rationale": "quote 1 was not found on page 23 of greens-ge2024 (not_found); copy it exactly",
      "modelConfidence": 0,
      "review": "pending"
    },
    {
      "questionId": 41,
      "fingerprint": "7105e74f",
      "rationale": "The documents discuss pension auto-enrolment and banning mandatory retirement before the state pension age, but never state whether the State Pension age itself should change.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 42,
      "fingerprint": "00dc0e15",
      "rationale": "The party promises a single national fee structure capping fees at low state-set levels, with free provision for lower-income families and a €200 monthly cap for others, matching answer 1.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 33,
          "pageLabel": "30",
          "text": "We will introduce a single national fee structure for public and private providers,",
          "quoteSha": "6c85fdfe81bfb8c7"
        },
        {
          "document": "greens-ge2024",
          "page": 34,
          "pageLabel": "31",
          "text": "Early years education and care will be provided free of charge to families on lower incomes.",
          "quoteSha": "5ddc192bfdd4dd69"
        }
      ]
    },
    {
      "questionId": 43,
      "fingerprint": "f906fd37",
      "rationale": "The documents discuss social welfare payments, means-testing, and a basic income, but do not address jobseeker's benefit linked to previous pay or its generosity/duration.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 44,
      "fingerprint": "396fad74",
      "rationale": "The party opposes a specific trade deal as bad for farmers and the environment, while still engaging in trade policy, matching answer 1 over open free trade or blanket opposition.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 30,
          "pageLabel": "27",
          "text": "Oppose the Mercosur trade deal in its current form, recognising it as a bad deal for farmers and the environment.",
          "quoteSha": "04cde81cb41798c0"
        }
      ]
    },
    {
      "questionId": 45,
      "fingerprint": "14dff138",
      "rationale": "The manifesto commits to reaching the 0.7% aid target and to progressively scaling up climate finance, matching gradual step-by-step progress rather than going beyond or cutting aid.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "greens-ge2024",
          "page": 72,
          "pageLabel": "69",
          "text": "We commit to spending 0.7% of our national income on overseas development aid, and to increasing climate finance to €500 million.",
          "quoteSha": "faa5a138f22fbdf6"
        }
      ]
    },
    {
      "questionId": 46,
      "fingerprint": "0dbe2725",
      "rationale": "This passage concerns the UN Security Council, not EU voting rules. The documents do not state a position on replacing the EU veto with majority voting on foreign policy or tax.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 47,
      "fingerprint": "6bdbf910",
      "rationale": "The documents discuss political reform, government structure and ministerial positions, but never address whether the Taoiseach should be able to appoint outside experts as ministers.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 48,
      "fingerprint": "afb38ef2",
      "rationale": "The documents discuss referendums the party would hold but do not address whether citizens should be able to trigger one by petition.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 49,
      "fingerprint": "16abd67c",
      "rationale": "The documents do not address Central Bank mortgage lending rules or who should set them.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    }
  ]
};
