// Generated by `npm run party-quiz`; edit fields only; comments are not kept.
import type { PartyQuizSheet } from '@shared/partyQuiz';

export const sheet: PartyQuizSheet = {
  "party": "Independent Ireland",
  "election": "ge2024",
  "documents": [
    "ii-ge2024"
  ],
  "model": "deepseek-flash",
  "promptVersion": "v2",
  "items": [
    {
      "questionId": 1,
      "fingerprint": "1ef56c01",
      "rationale": "The manifesto prioritises broad tax reductions for earners and households, matching answer 2 over infrastructure, social supports, or reserves.",
      "modelConfidence": 0.7,
      "review": "approved",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ii-ge2024",
          "page": 4,
          "pageLabel": null,
          "text": "We will expand lower rate tax bracket to earners under 75k per year. Abolish USC, Property Tax and PRSI for over 65's.",
          "quoteSha": "f0d9518d016de950"
        },
        {
          "document": "ii-ge2024",
          "page": 8,
          "pageLabel": null,
          "text": "Reduce middle-class taxes by ensuring no one earning less than €50,000 per annum is affected by the highest marginal rate of taxation;",
          "quoteSha": "cf8f67818604656d"
        }
      ]
    },
    {
      "questionId": 2,
      "fingerprint": "d9a4ede8",
      "rationale": "The documents do not address corporate tax rates, the 12.5% rate, EU minimum tax, or multinational tax competitiveness.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 3,
      "fingerprint": "ef513b0e",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 4,
      "fingerprint": "559f8cbf",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.55,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 5,
      "fingerprint": "bb8e1c30",
      "rationale": "The manifesto stresses age-appropriate content and keeping Irish culture, tradition and language central, matching a blend of modern citizenship with heritage and ethical continuity rather than rights/diversity emphasis.",
      "modelConfidence": 0.55,
      "review": "approved",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ii-ge2024",
          "page": 20,
          "pageLabel": null,
          "text": "Ensure all sexual education is age-appropriate;",
          "quoteSha": "e311ea85797ad000"
        }
      ]
    },
    {
      "questionId": 6,
      "fingerprint": "a3c40286",
      "rationale": "The manifesto backs a mixed public-private model via public-private partnerships and private hospital reimbursement, not a fully public system, mandatory insurance, or vouchers.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ii-ge2024",
          "page": 10,
          "pageLabel": null,
          "text": "Establish public-private partnerships to help shorten wait-times for medical care",
          "quoteSha": "7ff93d1f57674a29"
        }
      ]
    },
    {
      "questionId": 7,
      "fingerprint": "7a9221d8",
      "rationale": "The manifesto only addresses speech by opposing hate-speech laws; it says nothing about a personal freedoms bill, assembly, or reproductive rights, so it does not choose among the answers.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 8,
      "fingerprint": "f7fb5915",
      "rationale": "Manifesto pledges increased Irish-language funding and a mandatory Irish history/culture course for permanent residence applicants, matching answer 0's doubled language investment plus structured cultural induction for newcomers.",
      "modelConfidence": 0.75,
      "review": "approved",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ii-ge2024",
          "page": 23,
          "pageLabel": null,
          "text": "Increase funding for Irish language planning initiatives coordinated by Údarás na Gaeltachta to strengthen Irish as a community language.",
          "quoteSha": "458979f2b20fb0be"
        },
        {
          "document": "ii-ge2024",
          "page": 17,
          "pageLabel": null,
          "text": "Implement a requirement that permanent residence permit applicants must take a six-month course on Irish history and culture and pass an exam, provided in English and Irish only.",
          "quoteSha": "9319fe66cae4d817"
        }
      ]
    },
    {
      "questionId": 9,
      "fingerprint": "21820e1a",
      "rationale": "The manifesto supports densifying cities but conditions it on community buy-in, matching answer 3's call for a democratic mandate before proceeding. It does not endorse aggressive rezoning or preserving historic fabric outright.",
      "modelConfidence": 0.55,
      "review": "rejected",
      "status": "answered",
      "answerIndex": 3,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ii-ge2024",
          "page": 7,
          "pageLabel": null,
          "text": "Allow planning within cities to permit developers to build up within reason, and with community buy-in.",
          "quoteSha": "0d0807e50575b7f9"
        }
      ],
      "reviewNote": "Rejected 2026-10-05 after an independent read of the manifesto (unsupported): No passage on historic quarters, heritage buildings or citizens votes on planning. Only \"community buy-in\" for building up in cities, which is not a vote."
    },
    {
      "questionId": 10,
      "fingerprint": "308af8e2",
      "rationale": "The documents do not address arts funding or cultural policy at all.",
      "modelConfidence": 1,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 11,
      "fingerprint": "cb14689e",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 2
    },
    {
      "questionId": 12,
      "fingerprint": "dc35f0f4",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0,
      "review": "approved",
      "tentativeAnswerIndex": 2
    },
    {
      "questionId": 13,
      "fingerprint": "a7b1e486",
      "rationale": "Documents stress removing incentives and curbing supports for arrivals, opposing expansion of intake or integration services; they favour domestic capacity limits over doubling refugee numbers.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "answered",
      "answerIndex": 3,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ii-ge2024",
          "page": 16,
          "pageLabel": null,
          "text": "Curtail automatic medical cards to IPAS applicants, ensuring the same criteria is applied to IPAS applicants as is to existing residents",
          "quoteSha": "560954c5a2d335a4"
        },
        {
          "document": "ii-ge2024",
          "page": 17,
          "pageLabel": null,
          "text": "End private accommodation reimbursement altogether for future arrivals and eliminate the migrant housing industrial complex",
          "quoteSha": "af0c4ae8bb9492b0"
        }
      ]
    },
    {
      "questionId": 14,
      "fingerprint": "e081e7eb",
      "rationale": "The manifesto opposes any mandatory herd reduction and rejects the net-zero agenda, prioritising farm livelihoods over stretching climate delivery, matching answer 3.",
      "modelConfidence": 0.8,
      "review": "approved",
      "status": "answered",
      "answerIndex": 3,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ii-ge2024",
          "page": 12,
          "pageLabel": null,
          "text": "Oppose any mandatory cull of the national herd;",
          "quoteSha": "3b2c5b0c9b3c5fd1"
        },
        {
          "document": "ii-ge2024",
          "page": 18,
          "pageLabel": null,
          "text": "Abandon the unachievable and destructive “net-zero” agenda and adopt a common-sense approach that protects our economy and environment together instead of sacrificing one for the other;",
          "quoteSha": "49a76c93021001d6"
        }
      ]
    },
    {
      "questionId": 15,
      "fingerprint": "a2d8f793",
      "rationale": "The manifesto backs expanding floating gas terminals as a clean, reliable energy source, matching answer 3's transitional LNG approach; it rejects net-zero and does not endorse offshore wind, nuclear, or carbon capture.",
      "modelConfidence": 0.7,
      "review": "approved",
      "status": "answered",
      "answerIndex": 3,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ii-ge2024",
          "page": 18,
          "pageLabel": null,
          "text": "Expand use of floating gas terminals to provide a clean, reliable energy source",
          "quoteSha": "7a2067cec80d51cb"
        }
      ]
    },
    {
      "questionId": 16,
      "fingerprint": "25dadce4",
      "rationale": "The manifesto prioritises road widening and passing bays over congestion charging, and never proposes a congestion charge, matching answer 3's road upgrades and car freedom.",
      "modelConfidence": 0.7,
      "review": "rejected",
      "status": "answered",
      "answerIndex": 3,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ii-ge2024",
          "page": 19,
          "pageLabel": null,
          "text": "Pursue a road-widening campaign nationwide to improve road safety; increase construction of passing bays on local and regional roads;",
          "quoteSha": "5087bf6ffbe6d875"
        }
      ],
      "reviewNote": "Rejected 2026-10-05 after an independent read of the manifesto (unsupported): Manifesto never mentions a congestion charge. Quote is a road-widening road-safety pledge; rejecting the charge is an inference."
    },
    {
      "questionId": 17,
      "fingerprint": "471a3337",
      "rationale": "The manifesto addresses Garda resourcing, community policing and hate-speech opposition, but never mentions facial recognition or biometric surveillance, so it does not choose among the answers.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 18,
      "fingerprint": "edec1d4e",
      "rationale": "The documents address law and order, protest-related hate speech legislation, and free speech, but do not state a position on clearing, facilitating, negotiating, or protecting protests that block essential infrastructure.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 19,
      "fingerprint": "7842be43",
      "rationale": "The documents do not address pandemic response, public health emergencies, or any related measures such as restrictions, guidance, or shielding.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 20,
      "fingerprint": "f62bbcbf",
      "rationale": "The manifesto addresses welfare, taxes and employment but never mentions universal basic income, a pilot, or a universal payment, so no position on UBI is stated.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 21,
      "fingerprint": "1609def7",
      "rationale": "The manifesto incentivises private landlords via tax breaks and voluntary opt-outs rather than extending caps or state provision, matching answer 2.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ii-ge2024",
          "page": 6,
          "pageLabel": null,
          "text": "Achieve affordable rents for tenants by making tax-free all rents lower than €1,000",
          "quoteSha": "e9be926e146a94f5"
        }
      ]
    },
    {
      "questionId": 22,
      "fingerprint": "e1fb2ebb",
      "rationale": "The manifesto favours tax-free and strategic investment zones plus local enterprise funding to stimulate private-sector jobs in rural regions, matching answer 2 over direct exchequer grants, performance metrics, or relocation incentives.",
      "modelConfidence": 0.78,
      "review": "approved",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ii-ge2024",
          "page": 19,
          "pageLabel": null,
          "text": "Create “Green Technology and Innovation Tax-free Zones” for entities who create high-end jobs in rural areas.",
          "quoteSha": "2a7e1429804c7e1c"
        },
        {
          "document": "ii-ge2024",
          "page": 9,
          "pageLabel": null,
          "text": "Create a new strategic investment zone for Just Transition Areas to accelerate planning and improve employment opportunities in those areas",
          "quoteSha": "85eeb93ea6e6ec6d"
        }
      ]
    },
    {
      "questionId": 23,
      "fingerprint": "3ec07b23",
      "rationale": "The manifesto discusses technology, data centres, and green tech but never addresses AI-driven policy simulations or algorithmic governance, so no position on this question is stated.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 24,
      "fingerprint": "c06f1dff",
      "rationale": "The documents do not mention citizens' assemblies or any proposal to grant them binding authority over reforms.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 25,
      "fingerprint": "07c9b0b9",
      "rationale": "The manifesto proposes a private-sector-staffed Department of Efficiency and Reform with commissioners and audits to cut waste, matching answer 0's private-sector accountability over digital, mergers, or devolution.",
      "modelConfidence": 0.7,
      "review": "approved",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ii-ge2024",
          "page": 5,
          "pageLabel": null,
          "text": "Reduce government bureaucracy by leveraging private expertise.",
          "quoteSha": "81be5a4d5bdc9f31"
        },
        {
          "document": "ii-ge2024",
          "page": 5,
          "pageLabel": null,
          "text": "Appoint Commissioners for Public Expenditure through a competitive tender process targeting qualified private professionals",
          "quoteSha": "e40a6e2a1eead64b"
        }
      ]
    },
    {
      "questionId": 27,
      "fingerprint": "3ab3cc9b",
      "rationale": "The documents do not mention assisted dying, terminal illness, euthanasia, or end-of-life care anywhere in the manifesto text.",
      "modelConfidence": 1,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 28,
      "fingerprint": "fab89ead",
      "rationale": "The manifesto commits state funding and procurement for social/affordable housing built by private contractors, not a state construction company or private developers alone, matching answer 1.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ii-ge2024",
          "page": 7,
          "pageLabel": null,
          "text": "Overhaul public procurement policy to ensure contractors with track records of building in the public and private sectors can tender for the construction of affordable and social housing.",
          "quoteSha": "8e6b9322f4d42278"
        }
      ]
    },
    {
      "questionId": 29,
      "fingerprint": "3a36420a",
      "rationale": "The documents do not mention abortion, waiting periods, or related healthcare timing rules.",
      "modelConfidence": 1,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 30,
      "fingerprint": "429bf7e6",
      "rationale": "The documents address education funding, curriculum, and patronage-adjacent topics like opposing politicisation, but never discuss Catholic patronage of primary schools or whether it should change.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 31,
      "fingerprint": "095134aa",
      "rationale": "The manifesto covers housing, health, immigration, neutrality and many other areas, but contains no passage addressing surrogacy or assisted reproduction at all.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 32,
      "fingerprint": "6ac7c9a0",
      "rationale": "The documents do not mention the Angelus, RTÉ's daily broadcast, or any position on religious broadcasting.",
      "modelConfidence": 1,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 33,
      "fingerprint": "4e33e0ca",
      "rationale": "The documents discuss Irish language funding and education but never address whether Irish should remain compulsory for students up to the Leaving Certificate.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 34,
      "fingerprint": "7f8a2d2c",
      "rationale": "The documents do not address the naming of streets, bridges or public spaces, nor whose stories such names should reflect.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 35,
      "fingerprint": "2d90c7e8",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.55,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 2
    },
    {
      "questionId": 36,
      "fingerprint": "fc63dfdb",
      "rationale": "The manifesto addresses courts and sentencing but never mentions non-jury trials, the Special Criminal Court, or jury intimidation, so it states no position on whether judges-only trials should continue.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 37,
      "fingerprint": "37d5e83d",
      "rationale": "The documents discuss Garda recruitment, sentencing, and community policing but never address stop-and-search powers or reasonable suspicion.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 38,
      "fingerprint": "e90d2e5d",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.4,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 2
    },
    {
      "questionId": 39,
      "fingerprint": "206cd4cf",
      "rationale": "The manifesto pledges to freeze green taxes, which include carbon tax, and to review them, matching answer 3 (freeze then cut) better than keeping or pausing the legislated rise.",
      "modelConfidence": 0.8,
      "review": "approved",
      "status": "answered",
      "answerIndex": 3,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ii-ge2024",
          "page": 4,
          "pageLabel": null,
          "text": "We will freeze green taxes which are regressive and impact lower and middle income families the most.",
          "quoteSha": "0aaaaeb61735946c"
        },
        {
          "document": "ii-ge2024",
          "page": 8,
          "pageLabel": null,
          "text": "Freeze all “green taxes” – review the effectiveness of the stated purpose and adjust accordingly.",
          "quoteSha": "00ae0b7eec0a519c"
        }
      ]
    },
    {
      "questionId": 40,
      "fingerprint": "90aed241",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.55,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 2
    },
    {
      "questionId": 41,
      "fingerprint": "7105e74f",
      "rationale": "The documents do not mention the State Pension age or any proposal to change it; pension-related pledges concern tax relief and abolishing USC/PRSI for working pensioners, not the retirement age.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 42,
      "fingerprint": "00dc0e15",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.3,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 1
    },
    {
      "questionId": 43,
      "fingerprint": "f906fd37",
      "rationale": "The documents address PRSI only in the context of abolishing it for pension-aged workers and over-65s, not the generosity or duration of jobseeker's benefit linked to prior pay.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 44,
      "fingerprint": "396fad74",
      "rationale": "The manifesto explicitly opposes the Mercosur trade deal, a trade agreement exposing Irish farmers to cheaper imports, matching answer 3's protectionist stance over open-trade options.",
      "modelConfidence": 0.8,
      "review": "rejected",
      "status": "answered",
      "answerIndex": 3,
      "abstainReason": null,
      "quotes": [
        {
          "document": "ii-ge2024",
          "page": 12,
          "pageLabel": null,
          "text": "Oppose the Mercosur Trade deal; Introduce a specific Minister for fisheries responsible for maritime issues",
          "quoteSha": "7fcf36d66d80735b"
        }
      ],
      "reviewNote": "Rejected 2026-10-05 after an independent read of the manifesto (weak): Only \"Oppose the Mercosur Trade deal\" is stated; generalising to all deals that expose farmers is added. Option 2 fits about equally."
    },
    {
      "questionId": 45,
      "fingerprint": "14dff138",
      "rationale": "The documents do not mention overseas aid, the 0.7% UN target, or development assistance anywhere.",
      "modelConfidence": 1,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 46,
      "fingerprint": "0dbe2725",
      "rationale": "The documents discuss neutrality, opposing an EU Defence Force and supporting the triple-lock, but do not address EU voting rules or vetoes on foreign policy and tax.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 47,
      "fingerprint": "6bdbf910",
      "rationale": "The documents discuss appointing private-sector commissioners to a new Department of Efficiency and Reform, but do not address whether the Taoiseach should appoint outside experts as government ministers.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 48,
      "fingerprint": "afb38ef2",
      "rationale": "The documents discuss referendums only in the context of neutrality, requiring a referendum for any change, but do not address whether citizens can trigger one.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 49,
      "fingerprint": "16abd67c",
      "rationale": "The documents address housing and planning policy but never mention the Central Bank, mortgage lending limits, or who should set such rules.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    }
  ]
};
