// Generated by `npm run party-quiz`; edit fields only; comments are not kept.
import type { PartyQuizSheet } from '@shared/partyQuiz';

export const sheet: PartyQuizSheet = {
  "party": "Labour Party",
  "election": "ge2024",
  "documents": [
    "labour-ge2024"
  ],
  "model": "deepseek-flash",
  "promptVersion": "v2",
  "items": [
    {
      "questionId": 1,
      "fingerprint": "1ef56c01",
      "rationale": "Labour directs windfall funds to housing via a State Construction Company and to major public transport projects, matching answer 0's state-led infrastructure surge over tax relief, social supports or reserves.",
      "modelConfidence": 0.7,
      "review": "approved",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 41,
          "pageLabel": null,
          "text": "€7bn for housing deployed as follows: €6bn to seed a State Construction Company developed through the LDA.",
          "quoteSha": "5e6cf230def05ca7"
        },
        {
          "document": "labour-ge2024",
          "page": 41,
          "pageLabel": null,
          "text": "€2.5bn for major public transport projects and balanced regional development.",
          "quoteSha": "4e8001bbdfd95e66"
        }
      ]
    },
    {
      "questionId": 2,
      "fingerprint": "d9a4ede8",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.7,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 3,
      "fingerprint": "ef513b0e",
      "rationale": "Labour funds major public transport from exchequer windfall and a state development bank, with no private-partnership model for rail delivery, matching state borrowing and ownership.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 41,
          "pageLabel": null,
          "text": "€2.5bn for major public transport projects and balanced regional development.",
          "quoteSha": "4e8001bbdfd95e66"
        },
        {
          "document": "labour-ge2024",
          "page": 40,
          "pageLabel": null,
          "text": "Transform the Ireland Strategic Investment Fund (ISIF) and Strategic Banking Corporation of Ireland (SBCI) into an active Strategic Investment and Development Bank.",
          "quoteSha": "df7d8c9d71548a2a"
        }
      ]
    },
    {
      "questionId": 4,
      "fingerprint": "559f8cbf",
      "rationale": "Documents favour targeted support for low-income and vulnerable households (social tariffs, fuel allowance) rather than universal caps or pure market reliance, matching answer 1.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 33,
          "pageLabel": null,
          "text": "Develop social tariffs for heat pumps and households in energy poverty.",
          "quoteSha": "7f05ddca470bb012",
          "pageCorrected": true
        },
        {
          "document": "labour-ge2024",
          "page": 56,
          "pageLabel": null,
          "text": "Extend eligibility for the Fuel Allowance and adapt the scheme to ensure it meets the needs of vulnerable households",
          "quoteSha": "9a1400429d19ad73",
          "pageCorrected": true
        }
      ]
    },
    {
      "questionId": 5,
      "fingerprint": "bb8e1c30",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.3,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 2
    },
    {
      "questionId": 6,
      "fingerprint": "a3c40286",
      "rationale": "Labour backs Sláintecare's public model, extending free GP care to all and building public capacity, matching a fully public universal service rather than insurance, vouchers or profit-capped mixed provision.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 26,
          "pageLabel": null,
          "text": "Labour will deliver on the promise of Sláintecare with consistent funding and political follow through, ongoing reform and value for money to transform our health service.",
          "quoteSha": "38a8791049a81f67"
        },
        {
          "document": "labour-ge2024",
          "page": 27,
          "pageLabel": null,
          "text": "We will extend free GP to all, and ensure people have access to care at home, or at their local primary care centre",
          "quoteSha": "5c564053d7c5333a",
          "pageCorrected": true
        }
      ]
    },
    {
      "questionId": 7,
      "fingerprint": "7a9221d8",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.2,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 8,
      "fingerprint": "f7fb5915",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.7,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 9,
      "fingerprint": "21820e1a",
      "rationale": "The document proposes adding infill affordable housing while conserving historic buildings and streetscapes, matching answer 1: preserve exteriors, allow adaptive reuse inside.",
      "modelConfidence": 0.8,
      "review": "approved",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 118,
          "pageLabel": null,
          "text": "convert offices and add new infill public affordable housing while conserving the historic buildings, streetscapes, and public realm of the North Georgian core",
          "quoteSha": "e0ce695fffd8c450"
        }
      ]
    },
    {
      "questionId": 10,
      "fingerprint": "308af8e2",
      "rationale": "Labour pledges increased arts funding and a permanent Basic Income for the Arts, expanding access starting with younger artists, prioritising emerging voices and access over elite institutions or market-led models.",
      "modelConfidence": 0.8,
      "review": "approved",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 106,
          "pageLabel": null,
          "text": "Labour will increase funding to the Arts Council to €200 million per annum and ensure that the Arts represent a viable career",
          "quoteSha": "2de9dd546cf263b6"
        },
        {
          "document": "labour-ge2024",
          "page": 106,
          "pageLabel": null,
          "text": "Provide a permanent Basic Income for the Arts scheme and expand it to increase access, starting with younger artists.",
          "quoteSha": "9364cce91e6d20dd"
        }
      ]
    },
    {
      "questionId": 11,
      "fingerprint": "cb14689e",
      "rationale": "The manifesto commits to constitutional military neutrality and UN-approved peacekeeping via the Triple Lock, rejecting binding military aid to other states. This best matches declining EU defence force participation and prioritising UN peacekeeping.",
      "modelConfidence": 0.85,
      "review": "approved",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 126,
          "pageLabel": null,
          "text": "Labour is committed to retaining and protecting Ireland’s long-standing policy of military neutrality by amending our Constitution.",
          "quoteSha": "94c95cde673ee4d9",
          "pageCorrected": true
        },
        {
          "document": "labour-ge2024",
          "page": 126,
          "pageLabel": null,
          "text": "Retain the Triple Lock for approval of peacekeeping missions under the UN",
          "quoteSha": "35982cdeb32cc292",
          "pageCorrected": true
        }
      ]
    },
    {
      "questionId": 12,
      "fingerprint": "dc35f0f4",
      "rationale": "The manifesto backs EU CAP reform and EU-level measures like the Nitrates Derogation, supporting harmonised EU agricultural policy rather than opposing centralisation or devolving to regions.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 110,
          "pageLabel": null,
          "text": "Support CAP reforms that deliver a fairer distribution of income for small family and disadvantaged farmers, and rewards those who meet environmental and biodiversity criteria.",
          "quoteSha": "9ddb461798cc66bc"
        }
      ]
    },
    {
      "questionId": 13,
      "fingerprint": "a7b1e486",
      "rationale": "Documents commit to a fully resourced migration agency and nationwide integration strategy, matching answer 0's immediate expansion of integration services; no quota phasing or intake limits are stated.",
      "modelConfidence": 0.55,
      "review": "approved",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 121,
          "pageLabel": null,
          "text": "Labour will establish a new stand alone, fully resourced, and staffed agency for Integration, Migration and Asylum (AIMA) modelled on the Portuguese example",
          "quoteSha": "edc6d055e39f6ac8"
        },
        {
          "document": "labour-ge2024",
          "page": 122,
          "pageLabel": null,
          "text": "Labour will develop a new national migrant integration strategy, make available free English and Irish language, civics, and cultural courses to all migrants",
          "quoteSha": "fdefe26f4adc58fd",
          "pageCorrected": true
        }
      ]
    },
    {
      "questionId": 14,
      "fingerprint": "e081e7eb",
      "rationale": "Labour backs supporting farmers who exit dairy/beef and catchment strategies with lower stocking rates, matching mandated herd reduction with transition support rather than tech, offsets, or relaxed timelines.",
      "modelConfidence": 0.7,
      "review": "approved",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 111,
          "pageLabel": null,
          "text": "Support farmers who wish to exit dairy or beef for alternatives.",
          "quoteSha": "a7991478d1c0e752",
          "pageCorrected": true
        },
        {
          "document": "labour-ge2024",
          "page": 111,
          "pageLabel": null,
          "text": "To address nitrates, devise catchment-based strategies to reverse the decline in water quality attributable to excessive nutrient losses from livestock farming including for example lower stocking rates",
          "quoteSha": "7a121a4a36139a44",
          "pageCorrected": true
        }
      ]
    },
    {
      "questionId": 15,
      "fingerprint": "a2d8f793",
      "rationale": "The manifesto backs massive renewables, offshore wind equity stakes and grid upgrades, with no nuclear, CCS or LNG anchor; this matches answer 0 over the others.",
      "modelConfidence": 0.85,
      "review": "approved",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 23,
          "pageLabel": null,
          "text": "Labour will launch a new renewable energy strategy to ensure that at least 80% of Ireland’s electricity needs are met by renewable energy sources by 2030",
          "quoteSha": "0fc1959e3d27ecd1"
        }
      ]
    },
    {
      "questionId": 16,
      "fingerprint": "25dadce4",
      "rationale": "Labour supports a Dublin congestion charge but only after BusConnects is substantially delivered, matching answer 1's phase-in-after-delivery approach rather than immediate charging or rejection.",
      "modelConfidence": 0.82,
      "review": "approved",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 82,
          "pageLabel": null,
          "text": "Develop a model for a low emission zone congestion charge to incentivise public transport in Dublin when BusConnects is substantially delivered.",
          "quoteSha": "2c7db00e69a06f50"
        }
      ]
    },
    {
      "questionId": 17,
      "fingerprint": "471a3337",
      "rationale": "The manifesto opposes widespread FRT on civil-liberty grounds, matching answer 2's rejection of the proposal, though it allows carefully considered use with safeguards rather than a total ban.",
      "modelConfidence": 0.7,
      "review": "approved",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 84,
          "pageLabel": null,
          "text": "Labour supports the rollout of body worn cameras but is against the widespread use of Facial Recognition Technology due to serious concerns about privacy, trust, and data protection from mass surveillance.",
          "quoteSha": "9f885d6eeaddfeb8",
          "pageCorrected": true
        }
      ]
    },
    {
      "questionId": 18,
      "fingerprint": "edec1d4e",
      "rationale": "The manifesto pledges dedicated transport policing to address anti-social behaviour on public transport, supporting swift restoration of normal operations rather than dialogue-first or fully protecting disruption.",
      "modelConfidence": 0.4,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "tentativeAnswerIndex": 0,
      "quotes": []
    },
    {
      "questionId": 19,
      "fingerprint": "7842be43",
      "rationale": "The documents mention a Covid-19 public inquiry and pandemic preparedness but do not state a preferred public health approach for a new pandemic variant.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 20,
      "fingerprint": "f62bbcbf",
      "rationale": "The manifesto addresses income supports, welfare indexation and targeted payments, but never mentions universal basic income or a pilot, so it does not choose between these answers.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 21,
      "fingerprint": "1609def7",
      "rationale": "Labour backs a rent-increase and eviction freeze plus massive public home-building, matching answer 1's combination of immediate renter protection and accelerated public construction.",
      "modelConfidence": 0.8,
      "review": "approved",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 13,
          "pageLabel": null,
          "text": "We will introduce an immediate freeze on rent increases and evictions until housing supply dramatically increases",
          "quoteSha": "e5b0bb9aed3baf31"
        },
        {
          "document": "labour-ge2024",
          "page": 6,
          "pageLabel": null,
          "text": "Labour will build an annual average of 50,000 new homes over the next five years from 2025 to 2029",
          "quoteSha": "faca4dbc13894b3c"
        }
      ]
    },
    {
      "questionId": 22,
      "fingerprint": "e1fb2ebb",
      "rationale": "The manifesto proposes directing IDA/Enterprise Ireland activity outside the Eastern region and creating incentives and grants for towns lacking employers, matching answer 2's enterprise zones, tax incentives and local investment funds approach.",
      "modelConfidence": 0.7,
      "review": "approved",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 115,
          "pageLabel": null,
          "text": "We will give the IDA and Enterprise Ireland a renewed mandate to direct activity outside the Eastern region, and incentives and grants will be created to assist towns that lack larger employers",
          "quoteSha": "9a62557c6e6d5d29"
        },
        {
          "document": "labour-ge2024",
          "page": 115,
          "pageLabel": null,
          "text": "Labour will develop a new regional jobs and investment strategy that ensures new industrial opportunities are focused to the regions and towns that have been ignored for too long.",
          "quoteSha": "747c4524b4293af4"
        }
      ]
    },
    {
      "questionId": 23,
      "fingerprint": "3ec07b23",
      "rationale": "Documents endorse AI use but insist on human-centric, rights-based controls and regulation, keeping humans in control rather than letting algorithms steer decisions. This best matches answer 2, advisory technology with accountable human decision-makers.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 61,
          "pageLabel": null,
          "text": "Labour will adopt a human centric, rights-based approach to AI where people are the beneficiaries.",
          "quoteSha": "5dd5f371ff58cbac",
          "pageCorrected": true
        },
        {
          "document": "labour-ge2024",
          "page": 61,
          "pageLabel": null,
          "text": "Labour will ensure strong controls on workplace surveillance, algorithmic management, and recruitment.",
          "quoteSha": "3329b252aa619508",
          "pageCorrected": true
        }
      ]
    },
    {
      "questionId": 24,
      "fingerprint": "c06f1dff",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 2
    },
    {
      "questionId": 25,
      "fingerprint": "07c9b0b9",
      "rationale": "Manifesto frames public service reform around digitalisation and AI, plus digital tools in services, matching answer 1 over performance pay, agency mergers, or devolving discretion.",
      "modelConfidence": 0.7,
      "review": "approved",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 60,
          "pageLabel": null,
          "text": "Our mission is the inclusive transformation of our public services and economy through the benefits of digitalisation and AI",
          "quoteSha": "d763d50307be1cc1",
          "pageCorrected": true
        },
        {
          "document": "labour-ge2024",
          "page": 62,
          "pageLabel": null,
          "text": "Labour will increase the ICT grant for schools and ensure all children have access to modern learning methods such as tablets, not just those who can afford it.",
          "quoteSha": "f487aab7e8437fe0",
          "pageCorrected": true
        }
      ]
    },
    {
      "questionId": 27,
      "fingerprint": "3ab3cc9b",
      "rationale": "The manifesto commits to legislating for assisted dying with restricted circumstances and significant safeguards, matching answer 0 rather than a citizens' assembly, palliative-first delay, or maintaining the ban.",
      "modelConfidence": 0.85,
      "review": "approved",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 86,
          "pageLabel": null,
          "text": "Labour will develop a legislative framework for assisted dying in restricted circumstances and with significant safeguards in line with the recommendations of the Joint Committee report.",
          "quoteSha": "9af1b85cd0f2aa4f"
        }
      ]
    },
    {
      "questionId": 28,
      "fingerprint": "fab89ead",
      "rationale": "The manifesto commits to a State Construction Company that directly builds not-for-profit housing on state land, matching answer 0 over LDA-commissioning, private developers, or market-only approaches.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 7,
          "pageLabel": null,
          "text": "Labour believes in a State-led solution to the housing crisis, and we will transform the Land Development Agency into a State Construction Company (SCC)",
          "quoteSha": "04a93aa8a99278f1"
        }
      ]
    },
    {
      "questionId": 29,
      "fingerprint": "3a36420a",
      "rationale": "The manifesto commits to ending the three-day waiting period, matching answer 0's call to drop any mandatory wait.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 89,
          "pageLabel": null,
          "text": "Introduce reforms to the Regulation of Termination of Pregnancy Act 2019 to end the three-day waiting period",
          "quoteSha": "1fd7a8358b56daf2"
        }
      ]
    },
    {
      "questionId": 30,
      "fingerprint": "429bf7e6",
      "rationale": "Labour commits to an ambitious programme of patronage divestment to multi-denominational patrons, matching answer 0's firm national move rather than local or demand-led approaches.",
      "modelConfidence": 0.8,
      "review": "approved",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 64,
          "pageLabel": null,
          "text": "We will implement an ambitious programme of patronage divestment to multi-denominational patronage bodies like Educate Together and Education and Training Boards (ETBs) to provide more parental choice and recognise the growing diversity of our population.",
          "quoteSha": "b16905cd4715b82b"
        }
      ]
    },
    {
      "questionId": 31,
      "fingerprint": "095134aa",
      "rationale": "The manifesto addresses fertility treatments and assisted human reproduction only in passing (e.g. publicly funded fertility treatments, amending the Assisted Human Reproduction Act) but never states a position on whether surrogacy should be permitted, paid, or restricted.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 32,
      "fingerprint": "6ac7c9a0",
      "rationale": "The manifesto addresses broadcasting, media and public service broadcasting, but never mentions the Angelus or any daily religious devotion, so it does not choose between the answers.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 33,
      "fingerprint": "4e33e0ca",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 1
    },
    {
      "questionId": 34,
      "fingerprint": "7f8a2d2c",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.55,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 35,
      "fingerprint": "2d90c7e8",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 2
    },
    {
      "questionId": 36,
      "fingerprint": "fc63dfdb",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 1
    },
    {
      "questionId": 37,
      "fingerprint": "37d5e83d",
      "rationale": "The manifesto addresses policing powers and privacy safeguards but does not state a position on stop-and-search suspicion thresholds, so it does not choose between the answers.",
      "modelConfidence": 0.8,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 38,
      "fingerprint": "e90d2e5d",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 1
    },
    {
      "questionId": 39,
      "fingerprint": "206cd4cf",
      "rationale": "The documents address carbon tax but only commit to ringfencing revenues and offsetting increases for lower-income households; they never state whether the rate should rise faster, stay on the legislated path, pause, or be frozen or cut.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "no_preference",
      "quotes": []
    },
    {
      "questionId": 40,
      "fingerprint": "90aed241",
      "rationale": "The manifesto targets replacing existing oil and solid fuel heating, and proposes a Heat Pump Scheme funding installations, indicating a push to switch existing homes rather than leaving it to households.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 25,
          "pageLabel": null,
          "text": "Replacing oil boilers and solid fuel heating systems will have a significant impact on reducing our emissions and improving air quality over time",
          "quoteSha": "4f992ec3d85b5847",
          "pageCorrected": true
        }
      ]
    },
    {
      "questionId": 41,
      "fingerprint": "7105e74f",
      "rationale": "The manifesto explicitly commits to maintaining the State Pension age at 66, matching answer 1 (keep it at 66) and rejecting any increase or decrease.",
      "modelConfidence": 0.95,
      "review": "approved",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 55,
          "pageLabel": null,
          "text": "Labour will maintain the State Pension age of 66 and protect its value by implementing a pension promise linking it to 34% of average earnings.",
          "quoteSha": "4343e79b7feeefc8"
        }
      ]
    },
    {
      "questionId": 42,
      "fingerprint": "00dc0e15",
      "rationale": "Labour caps fees at €50/week for all families under a universal public system, with extra inclusion supports for children with disabilities, matching answer 1 rather than fully free care.",
      "modelConfidence": 0.8,
      "review": "approved",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 73,
          "pageLabel": null,
          "text": "Cap costs for parents at €50 per week, to bring the cost of childcare closer to average European levels.",
          "quoteSha": "963e68fee5a753bc",
          "pageCorrected": true
        },
        {
          "document": "labour-ge2024",
          "page": 36,
          "pageLabel": null,
          "text": "We will cap costs for parents at €50 per week and ensure children with disabilities have access to places through an expanded Access and Inclusion model.",
          "quoteSha": "51bb726e292bef12",
          "pageCorrected": true
        }
      ]
    },
    {
      "questionId": 43,
      "fingerprint": "f906fd37",
      "rationale": "The manifesto accepts pay-related jobseeker's benefits and proposes extending the pay-link principle to other benefits, indicating support for a more generous, earnings-linked payment rather than flat-rate or shortened support.",
      "modelConfidence": 0.6,
      "review": "approved",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 56,
          "pageLabel": null,
          "text": "Following the introduction of pay related jobseeker’s benefits, Labour will develop a roadmap of proposals to extend the principle to other social insurance benefits, starting with maternity benefit.",
          "quoteSha": "f6ea180fdeb80096"
        }
      ]
    },
    {
      "questionId": 44,
      "fingerprint": "396fad74",
      "rationale": "Labour supports open trade but conditions it: opposing deals with investment courts that undermine regulations, and protecting farmers from unfair competition. This matches answer 1, binding protections while continuing to trade, better than the other options.",
      "modelConfidence": 0.7,
      "review": "approved",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 127,
          "pageLabel": null,
          "text": "We will oppose trade agreements that include investment court systems that have the potential to undermine social and environmental regulations.",
          "quoteSha": "7091606407fb2f82"
        },
        {
          "document": "labour-ge2024",
          "page": 110,
          "pageLabel": null,
          "text": "Protect Irish farmers and agricultural workers from unfair competition and price speculation and ensure fair prices in the value chain.",
          "quoteSha": "c9ae8eddf83a3b87"
        }
      ]
    },
    {
      "questionId": 45,
      "fingerprint": "14dff138",
      "rationale": "The manifesto commits to reaching the 0.7% ODA target by 2030, matching answer 1's gradual, budget-by-budget approach rather than going beyond or cutting aid.",
      "modelConfidence": 0.7,
      "review": "approved",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "labour-ge2024",
          "page": 128,
          "pageLabel": null,
          "text": "Labour will meet our longstanding commitment of 0.7% of economic output for development assistance by 2030",
          "quoteSha": "99e385a47a2bfba7"
        }
      ]
    },
    {
      "questionId": 46,
      "fingerprint": "0dbe2725",
      "rationale": "The documents discuss EU enlargement, democratic reform and tax transparency but never address whether member-state vetoes on foreign policy or tax should be replaced by majority voting.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 47,
      "fingerprint": "6bdbf910",
      "rationale": "The manifesto discusses Oireachtas reform, ethics and accountability but never addresses whether the Taoiseach should appoint ministers from outside the Dáil or Seanad.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 48,
      "fingerprint": "afb38ef2",
      "rationale": "The documents discuss referendums Labour would hold and a Joint Committee on Constitutional Change, but never address whether citizens can trigger a referendum by petition or signature.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 49,
      "fingerprint": "16abd67c",
      "rationale": "The documents discuss housing, banking, and regulation but do not address who should set mortgage lending limits or the balance between the Central Bank and the Oireachtas on this matter.",
      "modelConfidence": 0.9,
      "review": "approved",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    }
  ]
};
