// Generated by `npm run party-quiz`; edit fields only; comments are not kept.
import type { PartyQuizSheet } from '@shared/partyQuiz';

export const sheet: PartyQuizSheet = {
  "party": "People Before Profit-Solidarity",
  "election": "ge2024",
  "documents": [
    "pbp-ge2024"
  ],
  "model": "deepseek-flash",
  "promptVersion": "v2",
  "items": [
    {
      "questionId": 1,
      "fingerprint": "1ef56c01",
      "rationale": "The documents prioritise a state-led construction surge for social and affordable housing, matching answer 0 over tax relief, reserves, or targeted supports.",
      "modelConfidence": 0.8,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "pbp-ge2024",
          "page": 6,
          "pageLabel": null,
          "text": "We need an emergency housing programme led by a State Construction Company to build many thousands of social and affordable houses.",
          "quoteSha": "bf71333ed85ee700"
        },
        {
          "document": "pbp-ge2024",
          "page": 7,
          "pageLabel": null,
          "text": "Use the State Construction Company to build 30,000 social and 5,000 affordable houses per year",
          "quoteSha": "7f09c0c662eb470d"
        }
      ]
    },
    {
      "questionId": 2,
      "fingerprint": "d9a4ede8",
      "rationale": "The manifesto commits to raising the corporate tax headline rate to 20% for large corporations, matching answer 2's call to raise headline rates, rather than holding 12.5% or merely complying with the EU minimum.",
      "modelConfidence": 0.85,
      "review": "pending",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "pbp-ge2024",
          "page": 12,
          "pageLabel": null,
          "text": "Raise Corporation Tax to 20% for large corporations and close tax avoidance loopholes to raise €20 billion in 2025.",
          "quoteSha": "0bfadd35fc95aa55"
        }
      ]
    },
    {
      "questionId": 3,
      "fingerprint": "ef513b0e",
      "rationale": "The manifesto commits to funding rail expansion through public money (the Future Ireland Fund) rather than private partnerships, matching state-led borrowing and ownership.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "pbp-ge2024",
          "page": 26,
          "pageLabel": null,
          "text": "Use billions of euros currently allocated to the Future Ireland Fund for capital investment in implementing the recommendations of the All-Island Rail Review",
          "quoteSha": "36f1a91258921889"
        }
      ]
    },
    {
      "questionId": 4,
      "fingerprint": "559f8cbf",
      "rationale": "The manifesto commits to capping energy prices and returning ESB to a not-for-profit mandate, matching a universal price cap shielding households rather than targeted rebates or market-based approaches.",
      "modelConfidence": 0.8,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "pbp-ge2024",
          "page": 10,
          "pageLabel": null,
          "text": "Cap essential food prices & cut electricity bills by returning ESB to a not for profit mandate and cap energy prices",
          "quoteSha": "37f0c97105278769"
        }
      ]
    },
    {
      "questionId": 5,
      "fingerprint": "bb8e1c30",
      "rationale": "The documents address education, including ending church control and objective Sex and Relationship Education, but do not state what emphasis a rewritten citizenship curriculum should carry.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 6,
      "fingerprint": "a3c40286",
      "rationale": "The manifesto backs a single-tier public system, free at point of delivery, with private hospitals taken into public ownership, matching answer 0 over mixed, insurance-based or voucher models.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "pbp-ge2024",
          "page": 14,
          "pageLabel": null,
          "text": "People Before Profit want a single tier system where patients are treated on the basis of need and services, including GP care, are provided free at the point of delivery.",
          "quoteSha": "d764d217916a8bb9"
        },
        {
          "document": "pbp-ge2024",
          "page": 15,
          "pageLabel": null,
          "text": "Take private hospitals into public ownership to expand capacity",
          "quoteSha": "7b3ec642fbe4f753"
        }
      ]
    },
    {
      "questionId": 7,
      "fingerprint": "7a9221d8",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "unverified_quote",
      "quotes": [],
      "rationale": "quote 2 was not found on page 22 of pbp-ge2024 (not_found); copy it exactly",
      "modelConfidence": 0,
      "review": "pending"
    },
    {
      "questionId": 8,
      "fingerprint": "f7fb5915",
      "rationale": "The manifesto funds Irish-language promotion and specifically allocates resources so refugees and asylum seekers in Gaeltacht areas can learn Irish, linking heritage investment with newcomer integration. This best matches answer 0.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "pbp-ge2024",
          "page": 35,
          "pageLabel": null,
          "text": "Allocate resources in Gaeltacht areas with a high number of refugees or asylum seekers to allow them to learn Irish.",
          "quoteSha": "4e8448c9105c78e5"
        },
        {
          "document": "pbp-ge2024",
          "page": 35,
          "pageLabel": null,
          "text": "Invest in promoting the Irish language among those who do not speak the language in the Gaeltachtaí and in particular, in the breac-Ghaeltachtaí",
          "quoteSha": "f6f72286b55d960e"
        }
      ]
    },
    {
      "questionId": 9,
      "fingerprint": "21820e1a",
      "rationale": "The documents address housing supply and heritage-related measures like vacant building reuse and referendums, but do not state a position on planning calls for historic quarters or choosing among these options.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 10,
      "fingerprint": "308af8e2",
      "rationale": "The manifesto prioritises community arts, new media and emerging artists over flagship institutions, matching answer 1.",
      "modelConfidence": 0.85,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "pbp-ge2024",
          "page": 36,
          "pageLabel": null,
          "text": "Provide additional funding to the Arts Council to increase the support for the arts and in particular new media art forms such as for computer animation, digital art, and video games, and expand allocation of funding to more artists",
          "quoteSha": "c467dd258e089fdf"
        }
      ]
    },
    {
      "questionId": 11,
      "fingerprint": "cb14689e",
      "rationale": "The manifesto rejects ending the triple lock and sending Irish troops to foreign wars, and pledges to defend neutrality fully, matching answer 2 (decline and protect neutrality) over joining any EU defence force.",
      "modelConfidence": 0.85,
      "review": "pending",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "pbp-ge2024",
          "page": 28,
          "pageLabel": null,
          "text": "Reject any moves to end the triple lock and expose efforts to send Irish troops to fight foreign wars",
          "quoteSha": "5a91e616d5408670"
        }
      ]
    },
    {
      "questionId": 12,
      "fingerprint": "dc35f0f4",
      "rationale": "The manifesto commits to capping dairy herds and reducing the national herd to cut emissions, showing support for climate-driven agricultural measures rather than opposing EU climate targets or seeking opt-outs.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "pbp-ge2024",
          "page": 25,
          "pageLabel": null,
          "text": "Therefore we would cap the size of herds to 200, introduce a voluntary scheme for those with less than 200.",
          "quoteSha": "758a9c4f97922e1d"
        },
        {
          "document": "pbp-ge2024",
          "page": 26,
          "pageLabel": null,
          "text": "Cap dairy herds at 200 cows and introduce a Dairy Herd Reduction scheme for farmers;",
          "quoteSha": "9b3f2cf94f1ba980"
        }
      ]
    },
    {
      "questionId": 13,
      "fingerprint": "a7b1e486",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 14,
      "fingerprint": "e081e7eb",
      "rationale": "The manifesto commits to capping and reducing the national dairy herd to cut agricultural emissions, matching answer 0's mandate for herd reduction, though it does not mention compensation for affected farmers.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "pbp-ge2024",
          "page": 25,
          "pageLabel": null,
          "text": "Therefore we would cap the size of herds to 200, introduce a voluntary scheme for those with less than 200.",
          "quoteSha": "758a9c4f97922e1d"
        },
        {
          "document": "pbp-ge2024",
          "page": 26,
          "pageLabel": null,
          "text": "Cap dairy herds at 200 cows and introduce a Dairy Herd Reduction scheme for farmers;",
          "quoteSha": "9b3f2cf94f1ba980"
        }
      ]
    },
    {
      "questionId": 15,
      "fingerprint": "a2d8f793",
      "rationale": "The manifesto backs a 100% renewable transition and bans new fossil fuel infrastructure including LNG, rejecting nuclear, CCS/green gas and transitional LNG. This matches answer 0's renewables-and-grid strategy best.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "pbp-ge2024",
          "page": 25,
          "pageLabel": null,
          "text": "Ban fossil fuel exploration and the construction of new fossil fuel infrastructure such as LNG",
          "quoteSha": "176c2b4c3dd40bfa"
        },
        {
          "document": "pbp-ge2024",
          "page": 25,
          "pageLabel": null,
          "text": "Develop a democratic plan to phase out fossil fuels and transition to 100% renewable energy",
          "quoteSha": "3913af6778960e3d"
        }
      ]
    },
    {
      "questionId": 16,
      "fingerprint": "25dadce4",
      "rationale": "The manifesto commits to abolishing public transport fares and free public transport, not introducing a congestion charge; it addresses transport pricing but rejects charging motorists, matching no answer.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "no_preference",
      "quotes": []
    },
    {
      "questionId": 17,
      "fingerprint": "471a3337",
      "rationale": "The manifesto addresses civil liberties, policing and surveillance-adjacent topics but never mentions facial recognition or biometric technology, so it takes no position on how far such a law should go.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 18,
      "fingerprint": "edec1d4e",
      "rationale": "The manifesto commits to repealing the Public Order Act to stop victimisation of protesters, indicating protection of protest rather than clearing it or penalising disruption.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 3,
      "abstainReason": null,
      "quotes": [
        {
          "document": "pbp-ge2024",
          "page": 39,
          "pageLabel": null,
          "text": "Repeal the Public Order Act to stop the victimisation of protesters",
          "quoteSha": "15a717f3d71f639d"
        }
      ]
    },
    {
      "questionId": 19,
      "fingerprint": "7842be43",
      "rationale": "The documents do not address pandemic response, public health emergencies, or any related measures such as restrictions, guidance, or local risk tailoring.",
      "modelConfidence": 1,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 20,
      "fingerprint": "f62bbcbf",
      "rationale": "The documents address income support through targeted measures like raising pensions and benefits, a living wage, and a Basic Income for the Arts pilot, but never discuss a nationwide universal basic income or choose between these options.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 21,
      "fingerprint": "1609def7",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.5,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 1
    },
    {
      "questionId": 22,
      "fingerprint": "e1fb2ebb",
      "rationale": "The manifesto commits exchequer resources and national programmes (State Construction Company, Apple money, extra funding for Gaeltacht bodies) to lift services and jobs in rural regions, matching direct central redistribution rather than tax incentives or relocation nudges.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "pbp-ge2024",
          "page": 35,
          "pageLabel": null,
          "text": "Support the supply of housing in the Gaeltacht. The State Construction Company, using the Apple Tax money, to work in liaison with Údarás.",
          "quoteSha": "ad0b2bb8b2bd597d"
        },
        {
          "document": "pbp-ge2024",
          "page": 34,
          "pageLabel": null,
          "text": "Acmhainní breise a chur ar fáil d’Údarás na Gaeltachta agus do Roinn na Gaeltachta le haghaidh infheistíochta agus tacaíochta sa Ghaeltacht.",
          "quoteSha": "125a67a847dd2cb6"
        }
      ]
    },
    {
      "questionId": 23,
      "fingerprint": "3ec07b23",
      "rationale": "The manifesto stresses mass participation and citizens' assemblies over expert-led or technocratic governance, matching answer 1's blend of expert input with participatory validation.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "pbp-ge2024",
          "page": 4,
          "pageLabel": null,
          "text": "It will require massive people power from below. This is why we encourage working people to organise, to feel their own strength and to push through the changes that are needed.",
          "quoteSha": "d290546593278456"
        },
        {
          "document": "pbp-ge2024",
          "page": 38,
          "pageLabel": null,
          "text": "People should play an active role in creating their destiny in a United Ireland through a series of citizens assemblies and a constituent assembly to draw up a new constitution",
          "quoteSha": "fef3e167cf2d8153"
        }
      ]
    },
    {
      "questionId": 24,
      "fingerprint": "c06f1dff",
      "rationale": "The document proposes citizens' assemblies and a constituent assembly to draw up a new constitution, implying a deliberative role in shaping reform, but it does not state whether such assemblies would have binding authority over legislation.",
      "modelConfidence": 0.2,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "no_preference",
      "quotes": []
    },
    {
      "questionId": 25,
      "fingerprint": "07c9b0b9",
      "rationale": "The documents criticise underfunding and call for investment in public services, but do not address productivity audits, performance contracts, digital transformation, agency mergers, or decentralising discretion.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 27,
      "fingerprint": "3ab3cc9b",
      "rationale": "The documents do not mention assisted dying, euthanasia, or end-of-life choice anywhere; the closest content concerns palliative care for children, which does not address the question.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 28,
      "fingerprint": "fab89ead",
      "rationale": "The manifesto commits to a State Construction Company building social and affordable homes directly, financed by the Apple money, matching answer 0 rather than relying on private developers or the LDA.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "pbp-ge2024",
          "page": 6,
          "pageLabel": null,
          "text": "We need an emergency housing programme led by a State Construction Company to build many thousands of social and affordable houses.",
          "quoteSha": "bf71333ed85ee700"
        }
      ]
    },
    {
      "questionId": 29,
      "fingerprint": "3a36420a",
      "rationale": "The manifesto explicitly commits to abolishing the mandatory 3-day wait period, matching answer 0 (drop any mandatory wait). No other answer is supported.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "pbp-ge2024",
          "page": 22,
          "pageLabel": null,
          "text": "Abolish the mandatory 3-day wait period;",
          "quoteSha": "d0d701e4e8cc60a7"
        }
      ]
    },
    {
      "questionId": 30,
      "fingerprint": "429bf7e6",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "unverified_quote",
      "quotes": [],
      "rationale": "quote 2 was not found on page 17 of pbp-ge2024 (too_short); copy it exactly",
      "modelConfidence": 0,
      "review": "pending"
    },
    {
      "questionId": 31,
      "fingerprint": "095134aa",
      "rationale": "The documents do not mention surrogacy or any related policy on assisted reproduction or family formation arrangements.",
      "modelConfidence": 1,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 32,
      "fingerprint": "6ac7c9a0",
      "rationale": "The documents discuss public broadcasting funding and reform but never mention the Angelus or any daily religious broadcast, so no position on this question is stated.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 33,
      "fingerprint": "4e33e0ca",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 3
    },
    {
      "questionId": 34,
      "fingerprint": "7f8a2d2c",
      "rationale": "The documents do not address the naming of streets, bridges or public spaces, nor whose stories such names should reflect.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 35,
      "fingerprint": "2d90c7e8",
      "rationale": "The documents do not address age verification for social media or under-16 access; the closest content concerns data centres, ICT taxes and online regulation, not minors' platform access.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 36,
      "fingerprint": "fc63dfdb",
      "rationale": "The manifesto commits to abolishing the non-jury Special Criminal Court and defending jury trial, matching answer 3 that every serious criminal trial should be heard by a jury.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "answered",
      "answerIndex": 3,
      "abstainReason": null,
      "quotes": [
        {
          "document": "pbp-ge2024",
          "page": 39,
          "pageLabel": null,
          "text": "Abolish the Special Criminal Court and defend the right to a jury trial.",
          "quoteSha": "2109ff95a73a4f7a"
        }
      ]
    },
    {
      "questionId": 37,
      "fingerprint": "37d5e83d",
      "rationale": "The documents discuss drug decriminalisation and policing as a health issue but never address Garda stop-and-search powers or reasonable suspicion.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 38,
      "fingerprint": "e90d2e5d",
      "rationale": "The manifesto calls for banning new data centres outright, which is stricter than pausing connections until renewables catch up, so answer 0 is closest.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "pbp-ge2024",
          "page": 25,
          "pageLabel": null,
          "text": "Ban any new data centres and monitor and restrict energy usage by existing data centres",
          "quoteSha": "c5181d1ccfd34d8f"
        }
      ]
    },
    {
      "questionId": 39,
      "fingerprint": "206cd4cf",
      "rationale": "The manifesto repeatedly commits to abolishing the carbon tax and replacing it with a levy on big polluters, matching answer 3 (freeze then cut) more than any other option.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "answered",
      "answerIndex": 3,
      "abstainReason": null,
      "quotes": [
        {
          "document": "pbp-ge2024",
          "page": 10,
          "pageLabel": null,
          "text": "Abolish the Carbon Tax: Put a levy on the big polluters instead",
          "quoteSha": "d3c462a31e34c23e"
        },
        {
          "document": "pbp-ge2024",
          "page": 25,
          "pageLabel": null,
          "text": "Abolish the carbon tax and instead impose a levy on big polluters",
          "quoteSha": "1e11fdb647bf58d5"
        }
      ]
    },
    {
      "questionId": 40,
      "fingerprint": "90aed241",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 41,
      "fingerprint": "7105e74f",
      "rationale": "Both passages commit to a pension age of 65, matching answer 0 (lower it to 65) and rejecting keeping 66 or raising it.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "pbp-ge2024",
          "page": 13,
          "pageLabel": null,
          "text": "The state pension to be paid at 65.",
          "quoteSha": "73fbe70e470bb61e"
        },
        {
          "document": "pbp-ge2024",
          "page": 21,
          "pageLabel": null,
          "text": "Restore the pension age to 65;",
          "quoteSha": "12c691c720eb65d8"
        }
      ]
    },
    {
      "questionId": 42,
      "fingerprint": "00dc0e15",
      "rationale": "The manifesto commits to a fully publicly funded National Childcare Service free for all parents, matching answer 0 rather than capped fees or income-targeted support.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "pbp-ge2024",
          "page": 18,
          "pageLabel": null,
          "text": "People Before Profit would transition rapidly to a fully publicly owned and funded National Childcare Service, available to all parents for free.",
          "quoteSha": "873bd6887f4ceaff"
        }
      ]
    },
    {
      "questionId": 43,
      "fingerprint": "f906fd37",
      "rationale": "The documents discuss jobseekers' allowance only in terms of ending discriminatory under-24 rates, not the pay-related benefit's generosity or duration.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 44,
      "fingerprint": "396fad74",
      "rationale": "The documents do not address EU trade deals or what Ireland should push for in them.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 45,
      "fingerprint": "14dff138",
      "rationale": "The documents do not mention overseas aid, the 0.7% UN target, or development assistance anywhere.",
      "modelConfidence": 1,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 46,
      "fingerprint": "0dbe2725",
      "rationale": "The documents do not address EU voting rules or the veto on foreign policy and tax decisions.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 47,
      "fingerprint": "6bdbf910",
      "rationale": "The documents do not address whether the Taoiseach should be able to appoint outside experts as ministers.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 48,
      "fingerprint": "afb38ef2",
      "rationale": "The documents discuss referendums the party would hold (e.g. on housing, water, rights of nature) but never address whether citizens can trigger a referendum by petition.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 49,
      "fingerprint": "16abd67c",
      "rationale": "The documents discuss mortgage interest caps and Central Bank powers but never address who should set mortgage lending limits or the balance between the Central Bank and the Oireachtas.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    }
  ]
};
