// Generated by `npm run party-quiz`; edit fields only; comments are not kept.
import type { PartyQuizSheet } from '@shared/partyQuiz';

export const sheet: PartyQuizSheet = {
  "party": "Sinn Féin",
  "election": "ge2024",
  "documents": [
    "sf-ge2024"
  ],
  "model": "deepseek-flash",
  "promptVersion": "v2",
  "items": [
    {
      "questionId": 1,
      "fingerprint": "1ef56c01",
      "rationale": "Windfall monies are earmarked for capital investment, especially housing and infrastructure, matching answer 0 over tax relief, reserves or social supports.",
      "modelConfidence": 0.8,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 170,
          "pageLabel": null,
          "text": "A Sinn Féin government will use the Apple tax money for capital investment in the areas that matter.",
          "quoteSha": "1e938f650ccacc55"
        },
        {
          "document": "sf-ge2024",
          "page": 171,
          "pageLabel": null,
          "text": "We will put €7.6 billion of the Apple tax money towards our public housing programme.",
          "quoteSha": "1a36c9e42188a149"
        }
      ]
    },
    {
      "questionId": 2,
      "fingerprint": "d9a4ede8",
      "rationale": "The manifesto commits to keeping the 12.5% rate while supporting the OECD agreement, matching answer 0's hold-the-rate stance rather than raising rates or pivoting from tax competition.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 175,
          "pageLabel": null,
          "text": "Sinn Féin support the OECD international tax agreement for those companies in scope and will maintain a corporation tax rate of 12.5%.",
          "quoteSha": "65302025ce754738"
        }
      ]
    },
    {
      "questionId": 3,
      "fingerprint": "ef513b0e",
      "rationale": "The manifesto rejects PPP contracts for public infrastructure, indicating state-led delivery rather than private partnerships, which best matches borrowing and building through a state agency.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 52,
          "pageLabel": null,
          "text": "Move away from the use of controversial PPP contracts for public infrastructure",
          "quoteSha": "376d7b4712d50c27",
          "pageCorrected": true
        }
      ]
    },
    {
      "questionId": 4,
      "fingerprint": "559f8cbf",
      "rationale": "The manifesto rejects market-led pass-through and instead reforms the energy market, PSO levy and network charges to keep prices affordable and equitable, matching a universal shielding approach rather than targeted rebates or pure income supports.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 125,
          "pageLabel": null,
          "text": "Sinn Féin would reorient Ireland’s energy system towards fairness, transparency, and affordability, ensuring energy companies are held to account",
          "quoteSha": "5d7bf6bd01adb6f7"
        },
        {
          "document": "sf-ge2024",
          "page": 126,
          "pageLabel": null,
          "text": "Reforming the PSO levy, Network Charges and other taxes to ensure costs are shared equitably",
          "quoteSha": "431425d2d69775c6"
        }
      ]
    },
    {
      "questionId": 5,
      "fingerprint": "bb8e1c30",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 6,
      "fingerprint": "a3c40286",
      "rationale": "The manifesto commits to a publicly funded, universal health system with full public cover by 2035, matching answer 0's fully public model rather than regulated private profit, mandatory insurance, or vouchers.",
      "modelConfidence": 0.8,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 20,
          "pageLabel": null,
          "text": "Our vision for an Irish NHS would deliver a publicly funded healthcare system for Ireland, which recognises physical and mental health as a human right.",
          "quoteSha": "29a6aa582dbd8656"
        },
        {
          "document": "sf-ge2024",
          "page": 21,
          "pageLabel": null,
          "text": "We would deliver a Healthcare for All Act to commit the state to full public health cover by 2035.",
          "quoteSha": "456964f3fb5d6bd1"
        }
      ]
    },
    {
      "questionId": 7,
      "fingerprint": "7a9221d8",
      "rationale": "The manifesto opposes new speech restrictions and would repeal hate offence laws, prioritising free speech over expanded regulation, aligning with rejecting the bill as drafted rather than passing it.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 3,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 92,
          "pageLabel": null,
          "text": "Sinn Féin would not introduce hate speech laws and we would repeal the government’s Criminal Justice (Hate Offences) Act because we believe that freedom of speech is a core component of democracy",
          "quoteSha": "68b646a04c9a979c"
        }
      ]
    },
    {
      "questionId": 8,
      "fingerprint": "f7fb5915",
      "rationale": "Documents promise major Irish-language investment and managed integration, but no passage pairs Irish-language groups with migrant organisations or mandates cultural induction for newcomers, so no answer is clearly matched.",
      "modelConfidence": 0.2,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "no_preference",
      "quotes": []
    },
    {
      "questionId": 9,
      "fingerprint": "21820e1a",
      "rationale": "The manifesto prioritises protecting heritage at risk and public access over developer profit, supporting keeping historic fabric intact rather than aggressive redevelopment.",
      "modelConfidence": 0.5,
      "review": "pending",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 143,
          "pageLabel": null,
          "text": "Expanding the OPW power to initiate a compulsory purchase of lands and buildings to cover heritage at risk and the defence of public access to sites",
          "quoteSha": "d6a8b838de4930dd"
        }
      ]
    },
    {
      "questionId": 10,
      "fingerprint": "308af8e2",
      "rationale": "Prioritises community arts, emerging voices and local access over elite institutions, with decentralised, inclusive funding and support for new media and artists nationwide.",
      "modelConfidence": 0.8,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 141,
          "pageLabel": null,
          "text": "Increasing funding to An Chomhairle Ealaíon (The Arts Council) by €60m providing multi-annual funding, and building on its work to create a more representative, decentralised, inclusive and democratic framework for the arts that serves communities nationwide",
          "quoteSha": "674c95c244a7c1a1"
        }
      ]
    },
    {
      "questionId": 11,
      "fingerprint": "cb14689e",
      "rationale": "The manifesto opposes EU militarisation and an EU army, and prioritises UN peacekeeping, matching answer 2 over joining any EU force.",
      "modelConfidence": 0.85,
      "review": "pending",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 162,
          "pageLabel": null,
          "text": "Opposing further militarisation within the European Union, including any prospects for the formation of an EU army",
          "quoteSha": "d01885128f5b6927"
        },
        {
          "document": "sf-ge2024",
          "page": 164,
          "pageLabel": null,
          "text": "Prioritising the deployment of Irish troops to UN-mandated peacekeeping missions around the world",
          "quoteSha": "9a680696dfdb0960"
        }
      ]
    },
    {
      "questionId": 12,
      "fingerprint": "dc35f0f4",
      "rationale": "The manifesto engages EU agri policy but only demands a higher CAP budget and protections in EU trade deals; it never endorses harmonised EU climate regulation, opt-outs, or opposing/devolving EU control, so no answer is clearly matched.",
      "modelConfidence": 0.3,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "no_preference",
      "quotes": []
    },
    {
      "questionId": 13,
      "fingerprint": "a7b1e486",
      "rationale": "The manifesto conditions intake on service and accommodation capacity, prioritising domestic constraints over expansion, matching answer 2's emphasis on capacity limits rather than doubling intake.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 158,
          "pageLabel": null,
          "text": "Sinn Féin believes that immigration must be managed having regard to the needs of the economy, public services and our capacity to accommodate and integrate additional people.",
          "quoteSha": "09e6fa6caaed6562"
        },
        {
          "document": "sf-ge2024",
          "page": 160,
          "pageLabel": null,
          "text": "Ensuring new IPAS centres are not placed in working class communities already under severe pressure.",
          "quoteSha": "80d018779c738e42"
        }
      ]
    },
    {
      "questionId": 14,
      "fingerprint": "e081e7eb",
      "rationale": "The manifesto funds nature restoration and biodiversity measures for farmers rather than mandating herd cuts or technology-only fixes, matching answer 2's offset approach; it does not choose herd reduction or relaxed timelines.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 83,
          "pageLabel": null,
          "text": "Sinn Féin would change this approach by ensuring support and funding come first. In government, we would establish a dedicated €300m nature restoration fund.",
          "quoteSha": "db03250807c78166"
        },
        {
          "document": "sf-ge2024",
          "page": 83,
          "pageLabel": null,
          "text": "Providing new funding for farmers outside of CAP for biodiversity and nature restoration measures, including a €300m dedicated nature restoration fund",
          "quoteSha": "a2d14cb76ead8242"
        }
      ]
    },
    {
      "questionId": 15,
      "fingerprint": "a2d8f793",
      "rationale": "Manifesto backs massive renewables, grid and port investment for offshore wind, with no support for nuclear, CCS or LNG. This matches answer 0 over the others.",
      "modelConfidence": 0.72,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 121,
          "pageLabel": null,
          "text": "Sinn Féin would accelerate the transition to renewable energy, transforming the state from import dependence to energy independence.",
          "quoteSha": "a173cd77d86bc266"
        },
        {
          "document": "sf-ge2024",
          "page": 123,
          "pageLabel": null,
          "text": "Ireland needs at least two ports to come anywhere close to our 5GW ambition for 2030.",
          "quoteSha": "af9fc4a52feba859"
        }
      ]
    },
    {
      "questionId": 16,
      "fingerprint": "25dadce4",
      "rationale": "The manifesto opposes charges on motorists who lack alternatives, prioritising road maintenance and offsetting tolls, which aligns with rejecting the charge and preserving car freedom rather than congestion pricing.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 3,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 53,
          "pageLabel": null,
          "text": "Sinn Féin would also offset the increase in toll costs. Amid a cost-of-living crisis, people with no alternative means of transport are being targeted, as they must use their cars and these toll roads.",
          "quoteSha": "56c81b0c8ac8371c"
        }
      ]
    },
    {
      "questionId": 17,
      "fingerprint": "471a3337",
      "rationale": "The manifesto addresses Garda recruitment, vetting, fraud and CCTV but never mentions facial recognition or biometric surveillance, so it states no position on how far such a law should go.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 18,
      "fingerprint": "edec1d4e",
      "rationale": "The manifesto addresses protest rights and policing generally, but no passage states a position on how to respond to protests blocking essential infrastructure.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 19,
      "fingerprint": "7842be43",
      "rationale": "The manifesto does not address pandemic response, public health restrictions, or any of the four approaches. No relevant position is stated in the documents.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 20,
      "fingerprint": "f62bbcbf",
      "rationale": "The documents discuss targeted welfare increases, a Social Welfare Adequacy Commission, and various pilot schemes, but never address a universal basic income or choose between these options.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 21,
      "fingerprint": "1609def7",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 1
    },
    {
      "questionId": 22,
      "fingerprint": "e1fb2ebb",
      "rationale": "The manifesto backs state enterprise agencies, local investment funds and regional development structures, matching answer 2's enterprise zones, tax incentives and local investment funds over central redistribution or relocation incentives.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 49,
          "pageLabel": null,
          "text": "Sinn Féin would pursue a multi-pronged industrial strategy to grow our domestic-oriented sector",
          "quoteSha": "32a68f1fa424d6da"
        },
        {
          "document": "sf-ge2024",
          "page": 50,
          "pageLabel": null,
          "text": "Establishing 'Mol Gnó', a new Irish Enterprise Agency, focused on scaling existing Irish businesses",
          "quoteSha": "127e93755305ca2a"
        }
      ]
    },
    {
      "questionId": 23,
      "fingerprint": "3ec07b23",
      "rationale": "The manifesto addresses AI only in relation to culture and media, not AI-driven policy simulations or decision-making tools for cabinet. No position on this governance question is stated.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 24,
      "fingerprint": "c06f1dff",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 2
    },
    {
      "questionId": 25,
      "fingerprint": "07c9b0b9",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 1
    },
    {
      "questionId": 27,
      "fingerprint": "3ab3cc9b",
      "rationale": "The manifesto does not address assisted dying or end-of-life choice; it only mentions palliative-adjacent commitments such as home care and disability services, not the legal question posed.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 28,
      "fingerprint": "fab89ead",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.4,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 2
    },
    {
      "questionId": 29,
      "fingerprint": "3a36420a",
      "rationale": "The manifesto does not address waiting periods or consultation requirements for abortion; it only mentions reproductive health in unrelated contexts such as contraception and gender identity services.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 30,
      "fingerprint": "429bf7e6",
      "rationale": "The manifesto commits to a strategy supporting demand for increased diversification of patronage, including multi-denominational schools, but frames it around existing and emerging demand rather than a firm national timetable, matching answer 2.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 64,
          "pageLabel": null,
          "text": "develop a new strategy to support existing and emerging demand for increased diversification of patronage in schools including state, co-educational, multi-denominational and community schools",
          "quoteSha": "5259a2c2e34462cd"
        }
      ]
    },
    {
      "questionId": 31,
      "fingerprint": "095134aa",
      "rationale": "The manifesto does not address surrogacy or what Irish law should allow regarding paid or unpaid surrogacy arrangements.",
      "modelConfidence": 1,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 32,
      "fingerprint": "6ac7c9a0",
      "rationale": "The documents discuss RTÉ funding and broadcasting policy but never mention the Angelus or any daily religious broadcast, so no position on this question is stated.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 33,
      "fingerprint": "4e33e0ca",
      "rationale": "The manifesto commits to keeping Irish at Leaving Cert and restoring Foundation Level at Junior Cert, ensuring every child studies Irish while providing a lighter course for those who struggle, matching answer 1.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 71,
          "pageLabel": null,
          "text": "Keeping Foundation Level at Leaving Cert, and restoring it at Junior Cert, to ensure every child has the opportunity to study Irish, irrespective of their standard, even if they attend an Irish medium school",
          "quoteSha": "c66f0f82d66d32a7"
        }
      ]
    },
    {
      "questionId": 34,
      "fingerprint": "7f8a2d2c",
      "rationale": "The manifesto endorses honouring Irish heroes in naming new infrastructure, matching answer 2 (mainly figures from Irish history) rather than newer communities or open nominations.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 144,
          "pageLabel": null,
          "text": "continuing the state’s tradition of honouring Ireland’s heroes when naming new housing developments and infrastructure",
          "quoteSha": "82754b5aaf19252f"
        }
      ]
    },
    {
      "questionId": 35,
      "fingerprint": "2d90c7e8",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 2
    },
    {
      "questionId": 36,
      "fingerprint": "fc63dfdb",
      "rationale": "The manifesto addresses policing, justice and organised crime but never mentions non-jury courts, the Special Criminal Court, or jury trials, so it states no position on this question.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 37,
      "fingerprint": "37d5e83d",
      "rationale": "The manifesto addresses policing and Garda recruitment but never discusses stop-and-search powers or reasonable suspicion, so no position on changing those powers is stated.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 38,
      "fingerprint": "e90d2e5d",
      "rationale": "The manifesto requires very high energy users, including data centres, to produce or fund additional renewable electricity matching their needs, matching answer 1 rather than pausing, treating them ordinarily, or prioritising them.",
      "modelConfidence": 0.85,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 123,
          "pageLabel": null,
          "text": "Introduce planning conditions that require prospective very high energy users to produce or contribute financially to the production of additional renewable electricity at least equal to their needs at any given time, ending tax relief to data centres",
          "quoteSha": "b36cb230459da712"
        }
      ]
    },
    {
      "questionId": 39,
      "fingerprint": "206cd4cf",
      "rationale": "The manifesto commits to halting all planned carbon tax increases through 2030, matching answer 3's freeze-then-cut position rather than continuing the legislated rise.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "answered",
      "answerIndex": 3,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 32,
          "pageLabel": null,
          "text": "we will ensure that all future planned carbon tax increases do not proceed and no increases in excise duty also during the five year term",
          "quoteSha": "f4c09c6270497260"
        },
        {
          "document": "sf-ge2024",
          "page": 174,
          "pageLabel": null,
          "text": "Stop all planned increase to the Carbon tax from 2025 – 2030.",
          "quoteSha": "1d4e1e720a07de2c"
        }
      ]
    },
    {
      "questionId": 40,
      "fingerprint": "90aed241",
      "rationale": "The manifesto proposes grants and a tiered retrofit scheme to help households switch, but never bans or mandates replacement of oil/gas boilers, matching answer 2 (grants for those who choose to switch).",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 127,
          "pageLabel": null,
          "text": "Overhauling the national retrofit programme so that more ordinary householders can afford to access retrofitting",
          "quoteSha": "86b6047eca25bf20"
        }
      ]
    },
    {
      "questionId": 41,
      "fingerprint": "7105e74f",
      "rationale": "The manifesto commits to restoring the right to retire at 65 by reintroducing the State Pension (Transition), matching answer 0 rather than keeping or raising the age.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 135,
          "pageLabel": null,
          "text": "Sinn Féin will continue to campaign for the right to retire at 65 on a pension for those who wish to do so.",
          "quoteSha": "fbfe9f0f21e41403"
        }
      ]
    },
    {
      "questionId": 42,
      "fingerprint": "00dc0e15",
      "rationale": "The manifesto caps fees at €10 per day for all families via provider subsidies, matching answer 1 (low fee cap for every family). It does not make childcare free, target only lower incomes, or replace subsidies with tax relief.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 28,
          "pageLabel": null,
          "text": "Sinn Féin is determined to deliver childcare to parents for €10 a day.",
          "quoteSha": "6f678da9c12d84f9"
        },
        {
          "document": "sf-ge2024",
          "page": 29,
          "pageLabel": null,
          "text": "Sinn Féin would deliver €10 a day childcare by giving subsidies to providers which bridge the gap between the actual costs of care and the €10 cap on the fees a parent can be charged per child.",
          "quoteSha": "d6afdf46c1be5a17"
        }
      ]
    },
    {
      "questionId": 43,
      "fingerprint": "f906fd37",
      "rationale": "The manifesto endorses pay-related benefits tied to previous earnings to prevent a sudden income drop, matching answer 0's more generous, earnings-linked approach.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 133,
          "pageLabel": null,
          "text": "Sinn Féin proposes linking the rate of Carers Benefit to a percentage of previous earnings, as is the norm in many other countries.",
          "quoteSha": "888569a9afdc6d35"
        },
        {
          "document": "sf-ge2024",
          "page": 133,
          "pageLabel": null,
          "text": "this would ensure that workers who have paid into the system are treated fairly and protected from a sudden push towards poverty",
          "quoteSha": "5ff3148b906977ec"
        }
      ]
    },
    {
      "questionId": 44,
      "fingerprint": "396fad74",
      "rationale": "The manifesto calls for EU trade deals to protect and support Irish farmers, and opposes the Mercosur Deal as putting farmers in a weaker position, matching answer 3's priority on shielding domestic producers from cheaper imports.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 3,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 81,
          "pageLabel": null,
          "text": "Ensuring EU free trade agreements protect and support Irish farmers",
          "quoteSha": "54b56217006ef2dc"
        }
      ]
    },
    {
      "questionId": 45,
      "fingerprint": "14dff138",
      "rationale": "The manifesto commits to reaching the 0.7% GNI aid target over the next government's lifetime, a gradual step-by-step path rather than quickly exceeding it or holding/cutting aid.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 154,
          "pageLabel": null,
          "text": "work towards meeting its international commitment to reach 0.7% GNI target for official development aid",
          "quoteSha": "93a80be1c27b18a3"
        },
        {
          "document": "sf-ge2024",
          "page": 155,
          "pageLabel": null,
          "text": "Increasing Ireland’s contributions to Official Development Aid to 0.7% of GNI over the lifetime of the next government",
          "quoteSha": "57e1e49d29deb61b"
        }
      ]
    },
    {
      "questionId": 46,
      "fingerprint": "0dbe2725",
      "rationale": "The manifesto opposes removing unanimity on foreign affairs and defence, and separately insists tax sovereignty must remain with member states, matching keeping the veto on both.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "sf-ge2024",
          "page": 152,
          "pageLabel": null,
          "text": "Opposing any attempts to transfer decision making powers on Foreign Affairs and Defence to the European Union and to remove unanimity on these matters",
          "quoteSha": "dc75150ee1d1f2e2"
        },
        {
          "document": "sf-ge2024",
          "page": 175,
          "pageLabel": null,
          "text": "We will defend our tax sovereignty and resist any attempts to cede any element of that sovereignty to the European Commission.",
          "quoteSha": "fd746815a549a5db"
        }
      ]
    },
    {
      "questionId": 47,
      "fingerprint": "6bdbf910",
      "rationale": "The manifesto addresses political reform and accountability but does not state a position on whether the Taoiseach should be able to appoint outside experts as ministers.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 48,
      "fingerprint": "afb38ef2",
      "rationale": "The documents discuss referendums the party would hold in government but do not address whether citizens should be able to trigger a referendum by petition.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 49,
      "fingerprint": "16abd67c",
      "rationale": "The documents do not address Central Bank mortgage lending rules or who should set them.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    }
  ]
};
