// Generated by `npm run party-quiz`; edit fields only; comments are not kept.
import type { PartyQuizSheet } from '@shared/partyQuiz';

export const sheet: PartyQuizSheet = {
  "party": "Social Democrats",
  "election": "ge2024",
  "documents": [
    "socdems-ge2024"
  ],
  "model": "deepseek-flash",
  "promptVersion": "v2",
  "items": [
    {
      "questionId": 1,
      "fingerprint": "1ef56c01",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0,
      "review": "pending",
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 2,
      "fingerprint": "d9a4ede8",
      "rationale": "The manifesto commits to broadening the tax base and raising revenue from high earners and wealth, rather than defending the 12.5% rate or relying on corporate tax competition. This aligns with raising headline rates and recycling revenue domestically.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "socdems-ge2024",
          "page": 114,
          "pageLabel": null,
          "text": "Ireland’s current over-reliance on temporary windfalls in corporation tax receipts is well-documented. In government we will set out a revenue-raising strategy to reduce this dependence through a broadening of the tax base.",
          "quoteSha": "43d3c9ef53309718"
        },
        {
          "document": "socdems-ge2024",
          "page": 115,
          "pageLabel": null,
          "text": "Increase the minimum effective income tax rate for people earning more than €400,000.",
          "quoteSha": "c073a8ca7de1d0ec"
        }
      ]
    },
    {
      "questionId": 3,
      "fingerprint": "ef513b0e",
      "rationale": "The manifesto commits to continued public funding of state-owned transport bodies and opposes privatisation, indicating delivery through public/state ownership rather than private partnerships.",
      "modelConfidence": 0.75,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "socdems-ge2024",
          "page": 53,
          "pageLabel": null,
          "text": "The continued public funding of state-owned public transport regulatory bodies, infrastructure providers, and transport operators to advance improvements in the public transport network for citizens",
          "quoteSha": "aaa34081aafcd461"
        },
        {
          "document": "socdems-ge2024",
          "page": 54,
          "pageLabel": null,
          "text": "Treating public transport as a public good, and opposing the increased privatisation of services.",
          "quoteSha": "434dca66ed7d8598",
          "pageCorrected": true
        }
      ]
    },
    {
      "questionId": 4,
      "fingerprint": "559f8cbf",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 1
    },
    {
      "questionId": 5,
      "fingerprint": "bb8e1c30",
      "rationale": "The documents favour removing faith formation from the school day and standardising an ethical, science-informed curriculum across all publicly funded schools, matching answer 0's emphasis on inclusive, equality-focused content over heritage or faith continuity.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "socdems-ge2024",
          "page": 62,
          "pageLabel": null,
          "text": "Aim to remove ‘faith formation’ from the school day, with it to be provided as an afterschool option, and use the time for a new ethical education programme as part of SPHE",
          "quoteSha": "c753dc342a5abc1f"
        },
        {
          "document": "socdems-ge2024",
          "page": 62,
          "pageLabel": null,
          "text": "Ensure children’s relationship and sexuality education that is informed by best practice in science and healthcare, with a standardised curriculum across all publicly funded schools.",
          "quoteSha": "b976eb5978f88907"
        }
      ]
    },
    {
      "questionId": 6,
      "fingerprint": "a3c40286",
      "rationale": "The documents back full Sláintecare implementation and reversing privatisation, with the State taking direct responsibility for provision, matching a rapid move to a fully public system over mixed, insurance-based or voucher models.",
      "modelConfidence": 0.85,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "socdems-ge2024",
          "page": 14,
          "pageLabel": null,
          "text": "Fully implement the Sláintecare programme within the term of the next government.",
          "quoteSha": "dde249e7ad38ceda"
        },
        {
          "document": "socdems-ge2024",
          "page": 17,
          "pageLabel": null,
          "text": "Reverse the trend of increased privatisation and take more direct responsibility for the provision of health and social care, in line with the principles underpinning Sláintecare.",
          "quoteSha": "f3b99b6c9c144cdb"
        }
      ]
    },
    {
      "questionId": 7,
      "fingerprint": "7a9221d8",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 8,
      "fingerprint": "f7fb5915",
      "rationale": "The documents commit to working with Irish-language community and advocacy groups and to integration measures, but never propose pairing Irish-language groups with migrant organisations, so no answer is clearly matched.",
      "modelConfidence": 0.2,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "no_preference",
      "quotes": []
    },
    {
      "questionId": 9,
      "fingerprint": "21820e1a",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 10,
      "fingerprint": "308af8e2",
      "rationale": "The document rejects cuts and prioritises funding to practising artists and emerging creative talent rather than flagship institutions, economic return, or private patronage, matching answer 1.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "socdems-ge2024",
          "page": 69,
          "pageLabel": null,
          "text": "Develop a roadmap for progressive increases in total arts funding, with a focus on current expenditure to practicing artists through the Arts Council and Culture Ireland.",
          "quoteSha": "c3f6c3d579d7dad1"
        }
      ]
    },
    {
      "questionId": 11,
      "fingerprint": "cb14689e",
      "rationale": "The party commits to retaining military neutrality and requires any major change to neutrality to be tested by Citizens' Assembly and possibly referendum, matching answer 3 over joining or declining outright.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 3,
      "abstainReason": null,
      "quotes": [
        {
          "document": "socdems-ge2024",
          "page": 142,
          "pageLabel": null,
          "text": "Retain Irelands long established policy of military neutrality (non-alignment) as a key element in our Foreign Policy",
          "quoteSha": "29da4b3771da0038"
        },
        {
          "document": "socdems-ge2024",
          "page": 142,
          "pageLabel": null,
          "text": "Ensure that any major change to our current form of neutrality, including the Triple Lock, will be tested first via a Citizens’ Assembly and possibly by referendum.",
          "quoteSha": "d1912def92c6ec21"
        }
      ]
    },
    {
      "questionId": 12,
      "fingerprint": "dc35f0f4",
      "rationale": "The party works within the EU CAP framework, seeking to strengthen its environmental conditions rather than oppose or exit it, matching answer 0's alignment with Brussels regulation.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "socdems-ge2024",
          "page": 41,
          "pageLabel": null,
          "text": "Demand a fairer and simpler Common Agricultural Policy which ensures more farm payments are targeted towards low-income farmers.",
          "quoteSha": "890c3d97789bc737"
        },
        {
          "document": "socdems-ge2024",
          "page": 41,
          "pageLabel": null,
          "text": "Seek to increase the environmental ambition around the CAP, ensuring farmers have access to payments only if they comply with a set of basic environmental norms.",
          "quoteSha": "fdbb1925cd828b3c"
        }
      ]
    },
    {
      "questionId": 13,
      "fingerprint": "a7b1e486",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 14,
      "fingerprint": "e081e7eb",
      "rationale": "The document explicitly links herd reduction to compensation via the Fair Transition Fund, matching answer 0 over technology, offsets, or relaxed timelines.",
      "modelConfidence": 0.85,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "socdems-ge2024",
          "page": 40,
          "pageLabel": null,
          "text": "Reduce methane emissions, using compensatory measures from the Fair Transition Fund for farmers to incentivise herd reduction.",
          "quoteSha": "b2240c3a05df8abc"
        }
      ]
    },
    {
      "questionId": 15,
      "fingerprint": "a2d8f793",
      "rationale": "The manifesto backs offshore wind, grid upgrades, interconnectors and becoming a net clean-energy exporter, matching answer 0. It opposes nuclear, CCS and LNG options, so answer 0 is clearly preferred.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "socdems-ge2024",
          "page": 51,
          "pageLabel": null,
          "text": "The goal would be to ensure secure energy supply and make Ireland a net exporter of energy.",
          "quoteSha": "25aa3deace05c3b1"
        },
        {
          "document": "socdems-ge2024",
          "page": 51,
          "pageLabel": null,
          "text": "Invest to improve the interconnectivity between Ireland and other countries.",
          "quoteSha": "f1293b15a4dd2e24"
        }
      ]
    },
    {
      "questionId": 16,
      "fingerprint": "25dadce4",
      "rationale": "The documents favour shifting investment from roads to public transport and endorse 'polluter pays' pricing, but never mention a congestion charge or phasing it after rail expansion, so no answer is clearly matched.",
      "modelConfidence": 0.3,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "no_preference",
      "quotes": []
    },
    {
      "questionId": 17,
      "fingerprint": "471a3337",
      "rationale": "The documents do not address facial recognition or Garda surveillance technology; the closest justice content concerns community policing and resourcing, not this proposal.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 18,
      "fingerprint": "edec1d4e",
      "rationale": "The documents do not address protest response or blocking infrastructure; no passage states a position on clearing, facilitating, negotiating, or protecting such protests.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 19,
      "fingerprint": "7842be43",
      "rationale": "The documents do not address pandemic response, mandatory restrictions, voluntary guidance, localised public health measures, or shielding high-risk groups.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 20,
      "fingerprint": "f62bbcbf",
      "rationale": "The document only mentions basic income as one option to explore in a cross-government analysis of automation-driven labour displacement, not a nationwide UBI commitment or pilot. This does not clearly match any answer.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "no_preference",
      "quotes": []
    },
    {
      "questionId": 21,
      "fingerprint": "1609def7",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "unverified_quote",
      "quotes": [],
      "rationale": "quote 1 was not found on page 11 of socdems-ge2024 (too_short); copy it exactly",
      "modelConfidence": 0,
      "review": "pending"
    },
    {
      "questionId": 22,
      "fingerprint": "e1fb2ebb",
      "rationale": "The party proposes direct state investment in capital projects and relocation of state agencies to regions, matching answer 0's central redistribution through national programmes rather than tax incentives or performance-tied funding.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "socdems-ge2024",
          "page": 103,
          "pageLabel": null,
          "text": "Promote regional economic development by investing in capital projects that boost industrial and commercial capacity across the country",
          "quoteSha": "7868c46a22b60e8c"
        },
        {
          "document": "socdems-ge2024",
          "page": 103,
          "pageLabel": null,
          "text": "Increase the regional spread of civil service and state agencies, in a way that has buy-in from all stakeholders and builds on lessons from previous redeployments.",
          "quoteSha": "8033809c75fce37a"
        }
      ]
    },
    {
      "questionId": 23,
      "fingerprint": "3ec07b23",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 1
    },
    {
      "questionId": 24,
      "fingerprint": "c06f1dff",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 2
    },
    {
      "questionId": 25,
      "fingerprint": "07c9b0b9",
      "rationale": "The documents propose a real-time spending watchdog and consolidating programmes to modernise departments, matching answer 2's merge/streamline approach; they do not propose performance bonuses, digital transformation, or devolving discretion.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "answered",
      "answerIndex": 2,
      "abstainReason": null,
      "quotes": [
        {
          "document": "socdems-ge2024",
          "page": 120,
          "pageLabel": null,
          "text": "The Government Accountability Office would: Perform the role of a public spending watchdog in real-time.",
          "quoteSha": "ee16585adba2260c"
        },
        {
          "document": "socdems-ge2024",
          "page": 120,
          "pageLabel": null,
          "text": "Work to eliminate wasteful or duplicative spending, consolidate programmes, and modernise how government departments work to save money and improve performance.",
          "quoteSha": "5b7080153ca3acde"
        }
      ]
    },
    {
      "questionId": 27,
      "fingerprint": "3ab3cc9b",
      "rationale": "The manifesto commits to supporting legislation for assisted dying on a limited basis, matching answer 0's call to legislate now for terminally ill adults with safeguards.",
      "modelConfidence": 0.8,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "socdems-ge2024",
          "page": 130,
          "pageLabel": null,
          "text": "Support legislation to introduce Assisted Dying on a limited basis in Ireland.",
          "quoteSha": "34cfe881e2199363"
        }
      ]
    },
    {
      "questionId": 28,
      "fingerprint": "fab89ead",
      "rationale": "The party wants the State and not-for-profit sector at the heart of delivery, directly building social and affordable homes via local authorities and AHBs, rejecting developer handouts and leasing. This matches state-led building at cost, not private developers.",
      "modelConfidence": 0.8,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "socdems-ge2024",
          "page": 9,
          "pageLabel": null,
          "text": "The Social Democrats believe the State and the not-for-profit sector should be at heart of housing delivery.",
          "quoteSha": "ce17ffdd4449a591"
        },
        {
          "document": "socdems-ge2024",
          "page": 9,
          "pageLabel": null,
          "text": "End lucrative long-term leasing deals for social housing provision, in favour of the direct building of social homes by local authorities.",
          "quoteSha": "6bcc76beafd8f1b0"
        }
      ]
    },
    {
      "questionId": 29,
      "fingerprint": "3a36420a",
      "rationale": "The document commits to removing the three-day waiting period, matching answer 0's call to drop any mandatory wait.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "socdems-ge2024",
          "page": 20,
          "pageLabel": null,
          "text": "Implement in full the recommendations of the O’Shea Review into the operation of the Health (Regulation of Termination of Pregnancy) Act 2018, including removing the three-day waiting period for access to abortion services",
          "quoteSha": "6224175927195d47"
        }
      ]
    },
    {
      "questionId": 30,
      "fingerprint": "429bf7e6",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.4,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 31,
      "fingerprint": "d25e0921",
      "rationale": "The documents do not address surrogacy or how Irish law should treat it; the Assisted Human Reproduction Act is mentioned only in passing regarding LGBTQI+ parent recognition.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": [],
      "stale": true
    },
    {
      "questionId": 32,
      "fingerprint": "6ac7c9a0",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.7,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 0
    },
    {
      "questionId": 33,
      "fingerprint": "4e33e0ca",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 2
    },
    {
      "questionId": 34,
      "fingerprint": "7f8a2d2c",
      "rationale": "The documents do not address the naming of streets, bridges or public spaces, nor whose stories such names should tell.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 35,
      "fingerprint": "2d90c7e8",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.55,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 1
    },
    {
      "questionId": 36,
      "fingerprint": "fc63dfdb",
      "rationale": "The documents discuss justice and penal reform but do not address non-jury courts or jury trials for terrorism or gangland cases.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 37,
      "fingerprint": "37d5e83d",
      "rationale": "The documents address Garda resourcing, community policing and drug decriminalisation, but never discuss stop-and-search powers or reasonable suspicion. No stated position matches any answer.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 38,
      "fingerprint": "e90d2e5d",
      "rationale": "The document commits to a moratorium on data centre development and planning decisions pending impact analysis, matching a pause on new connections until supply and grid catch up.",
      "modelConfidence": 0.85,
      "review": "pending",
      "status": "answered",
      "answerIndex": 0,
      "abstainReason": null,
      "quotes": [
        {
          "document": "socdems-ge2024",
          "page": 49,
          "pageLabel": null,
          "text": "Enact a moratorium on the development of data centres and the issuing of planning decisions as an interim measure until an economic, environmental and energy impact risk analysis has been carried out.",
          "quoteSha": "16d7cf28320ed693"
        }
      ]
    },
    {
      "questionId": 39,
      "fingerprint": "206cd4cf",
      "rationale": "The documents discuss carbon pricing only indirectly, via a 'polluter pays' principle and transport fiscal measures, but never address the carbon tax trajectory or whether to raise, keep, pause, freeze or cut it.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 40,
      "fingerprint": "90aed241",
      "rationale": "The answer changed when the options were shown in a different order, so it is not kept.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "low_confidence",
      "quotes": [],
      "tentativeAnswerIndex": 2
    },
    {
      "questionId": 41,
      "fingerprint": "7105e74f",
      "rationale": "The documents address pensions only by linking the State Pension to wages and indexing payments; they do not state a position on changing the pension age.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 42,
      "fingerprint": "00dc0e15",
      "rationale": "The document commits to capping childcare fees for all families while setting a lower cap for lower-income households, matching answer 1 rather than free universal care or income-targeted-only support.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "socdems-ge2024",
          "page": 78,
          "pageLabel": null,
          "text": "Ensure affordability for parents, by capping fees at €250 per child per month, with a cap of €200 for lower income households.",
          "quoteSha": "2523fdcb5ea115e1"
        }
      ]
    },
    {
      "questionId": 43,
      "fingerprint": "f906fd37",
      "rationale": "The documents discuss social welfare benchmarking and low income but do not address jobseeker's benefit linked to previous pay or its duration/generosity.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 44,
      "fingerprint": "396fad74",
      "rationale": "The documents back open trade but insist on binding standards and protections for sensitive farming sectors, matching answer 1 rather than pure free trade or outright opposition.",
      "modelConfidence": 0.6,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "socdems-ge2024",
          "page": 43,
          "pageLabel": null,
          "text": "Oppose unfair competition to European farmers from products that do not respect the same standards that they adhere to, including from countries outside the EU.",
          "quoteSha": "13a34880118410d3"
        },
        {
          "document": "socdems-ge2024",
          "page": 42,
          "pageLabel": null,
          "text": "Work with our European partners to achieve flexibility around state aid rules, including permitting schemes to protect the most precarious parts of the Agri-Food sector.",
          "quoteSha": "218126e5c9aef025"
        }
      ]
    },
    {
      "questionId": 45,
      "fingerprint": "14dff138",
      "rationale": "The document commits to reaching the 0.7% UN aid target by 2030, a gradual step-by-step timeline rather than quickly going beyond it or holding/cutting aid.",
      "modelConfidence": 0.8,
      "review": "pending",
      "status": "answered",
      "answerIndex": 1,
      "abstainReason": null,
      "quotes": [
        {
          "document": "socdems-ge2024",
          "page": 144,
          "pageLabel": null,
          "text": "Reaching the UN target of allocating 0.7 per cent of national income to official development assistance (ODA) not later than 2030.",
          "quoteSha": "e76271e3cd818169"
        }
      ]
    },
    {
      "questionId": 46,
      "fingerprint": "0dbe2725",
      "rationale": "The documents address EU cooperation on tax and foreign policy but do not state a position on replacing unanimity/veto with majority voting in either area.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 47,
      "fingerprint": "6bdbf910",
      "rationale": "The documents do not address whether the Taoiseach should be able to appoint outside experts as ministers; no passage discusses ministerial eligibility or appointments from outside the Oireachtas.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 48,
      "fingerprint": "afb38ef2",
      "rationale": "The documents do not address whether citizens can trigger a referendum; no passage discusses referendum initiation or citizens' initiatives.",
      "modelConfidence": 0.9,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    },
    {
      "questionId": 49,
      "fingerprint": "16abd67c",
      "rationale": "The documents do not address Central Bank mortgage lending rules or who should set them.",
      "modelConfidence": 0.95,
      "review": "pending",
      "status": "abstained",
      "answerIndex": null,
      "abstainReason": "silent",
      "quotes": []
    }
  ]
};
