// Generated by `npm run party-quiz` from the sheet files; do not edit.
import type { PartyQuizSheet } from '@shared/partyQuiz';
import { sheet as ge2024_aontu } from './ge2024/aontu';
import { sheet as ge2024_fiannafail } from './ge2024/fiannafail';
import { sheet as ge2024_finegael } from './ge2024/finegael';
import { sheet as ge2024_green } from './ge2024/green';
import { sheet as ge2024_independentireland } from './ge2024/independentireland';
import { sheet as ge2024_labour } from './ge2024/labour';
import { sheet as ge2024_peoplebeforeprofitsolidarity } from './ge2024/peoplebeforeprofitsolidarity';
import { sheet as ge2024_sinnfein } from './ge2024/sinnfein';
import { sheet as ge2024_socialdemocrats } from './ge2024/socialdemocrats';

export const SHEETS: PartyQuizSheet[] = [ge2024_aontu, ge2024_fiannafail, ge2024_finegael, ge2024_green, ge2024_independentireland, ge2024_labour, ge2024_peoplebeforeprofitsolidarity, ge2024_sinnfein, ge2024_socialdemocrats];
