/**
 * The party quiz: each party "takes" the quiz from its manifesto, one answer sheet per party
 * and election. A sheet is generated by the party-quiz CLI, reviewed by a person in a git PR,
 * and compiled into the build (server/partyQuiz/sheets). The repo is public, so a sheet holds
 * only short capped quotes, never the manifesto text.
 */

export const ELECTIONS = ['ge2024'] as const;
export type Election = (typeof ELECTIONS)[number];

/**
 * Why a party gave no answer. The first three are the model's reading of the document; the
 * last two are set by the CLI when the model's answer could not be kept.
 */
export const ABSTAIN_REASONS = ['silent', 'no_preference', 'contradictory', 'unverified_quote', 'low_confidence'] as const;
export type AbstainReason = (typeof ABSTAIN_REASONS)[number];

/** Only `approved` items are ever scored or served. */
export const REVIEW_STATES = ['pending', 'approved', 'rejected'] as const;
export type ReviewState = (typeof REVIEW_STATES)[number];

export type PartyQuizItemStatus = 'answered' | 'abstained';

export interface PartyQuizQuote {
  /** Registry slug of the document. */
  document: string;
  /** Page ordinal in the stored text: the citation unit. */
  page: number;
  /** The page number printed on the page, when it differs or is known. */
  pageLabel: string | null;
  text: string;
  /** First 16 hex of sha256(skeleton(text)); catches a quote edited after it was verified. */
  quoteSha: string;
  /** The model cited another page; the quote was found on exactly one other page. */
  pageCorrected?: boolean;
}

export interface PartyQuizItem {
  questionId: number;
  /** questionFingerprint of the question when it was answered; a mismatch means stale. */
  fingerprint: string;
  status: PartyQuizItemStatus;
  answerIndex: number | null;
  abstainReason: AbstainReason | null;
  /** For `low_confidence`: the answer the model leaned to, kept for review only. */
  tentativeAnswerIndex?: number;
  quotes: PartyQuizQuote[];
  rationale: string;
  /** A review aid, never a scoring weight. */
  modelConfidence: number;
  review: ReviewState;
  reviewerEdited?: boolean;
  reviewNote?: string;
  stale?: boolean;
}

export interface PartyQuizSheet {
  /** `tds.party` label. */
  party: string;
  election: Election;
  /** Registry slugs of the documents the model read. */
  documents: string[];
  /** The model that actually answered (completion.model). */
  model: string;
  promptVersion: string;
  items: PartyQuizItem[];
}
